### ISSUE TITLE
Publish @next CLI, plug-ins and SDKs to the Zowe Technical Preview Section on Zowe Downloads

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1005]
Add `@next` distributions of Zowe CLI, Zowe CLI Plug-ins, and the SDKs to the Zowe Technical Preview Section on [Zowe Downloads](https://www.zowe.org/download.html).   Also include SDK typedoc.

**Comment by MikeBauerCA** [comment]
Note - brief Zowe Explorer team (@jellypuno) on the process during this initiative

**Comment by JTonda** [comment]
These distributions will be updated as the same cadence of the LTS distributions.

**Comment by t1m0thyj** [comment]
The downloads will be hosted in the "libs-snapshot-local" repo on Zowe Artifactory. Other downloads must be promoted to "libs-release-local", but we can skip this process since the "next" release is a snapshot instead of a fixed version.

The SDK reference doc will be hosted on the Zowe docs site, in a "typedoc_next" folder alongside the existing LTS typedoc: https://github.com/zowe/docs-site/tree/master/docs/.vuepress/public

**Comment by t1m0thyj** [comment]
* [ ] Merge https://github.com/zowe/zowe-cli-standalone-package/pull/32 into master branch
* [ ] Delete next branch of zowe-cli-standalone-package
* [ ] Publish "next" typedoc to Zowe docs site
* [ ] Get confirmation from Jack J./Mark A. about publish URL for "next" bundles
* [ ] Merge https://github.com/zowe/zowe.github.io/pull/167 for Zowe 1.23 release

**Comment by jellypuno** [comment]
Tagging @crawr for awareness

**Comment by zFernand0** [comment]
Seems like this issue can be closed.
https://www.zowe.org/download.html
@t1m0thyj, thoughts?
