### ISSUE TITLE
Zowe CLI syslog browse ability.

### ISSUE THREAD

**Issue by frankgiordano** [zowe/zowe-cli#1008]
Is there a way to browse SYSLOG output via zowe cli or zowe client sdk. I cant find such a way. Is this planned for the future?

**Comment by MikeBauerCA** [comment]
@frankgiordano not at this time - however, you could leverage the [SYSVIEW plug-in for Zowe CLI](https://www.npmjs.com/package/@broadcom/sysview-for-zowe-cli) if SYSVIEW is available for you.

There are a couple caveats with this
 - You would have to use the JSYSLOGW command instead of SYSLOG, for technical API reasons
 - That's one of the commands that scrolls to the bottom, but the API normally returns data starting at the top. To retrieve the most recent data, you'll have to use the LINES parameter (minimum of 1000), and you'll need to request at least that many from the REST API. for example,
`zowe sysview display "JSYSLOGW LINES 1500" --row-end 1500`

**Comment by frankgiordano** [comment]
@MikeBauerCA I am trying sysview plugin.. but I cant seem to get it to work. can you help me?

C:\Users\fg892105\IdeaProjects\ZoweCCSSanityChecksPOC>zowe sysview display "JSYSLOGW LINES 1500" --row-end 1500
Command Error:
Rest API failure with HTTP(S) status 404
Error Details:
HTTP(S) error status "404" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Protocol:  https
Host:      usilCA31.lvn.broadcom.net
Port:      1443
Base Path: /api/v1
Resource:  SYSVIEW/Display?command=JSYSLOGW%20LINES%201500&rowstart=1&rowend=1500&types=CONTEXT%3BDATAROWS&ssid=GSVX&timeout=30
Request:   GET
Headers:   []
Payload:   undefined

I did not specify ssid when create the zowe sysview profile. Maybe my ssid value is incorrect. I dont know what value to specify for ssid if that is the case.

Thoughts? 

Thanks much.

**Comment by MikeBauerCA** [comment]
Sure, @frankgiordano - it is a connection issue - I will reach out to you

**Comment by frankgiordano** [comment]
@MikeBauerCA @tucker01 thanks I was able to get the sysview plugin to work and implemented in my nodejs app this is nice as I can retrieve by line limit.. the other workaround as noted would give me too large of a set of info to parse. My goal is to retrieve a small window of info every morning for some monitoring purposes. We can close this issue if you want. But a by line limit cli call out of box for syslog viewing would be nice. But I guess that is what third parties like sysview plugin exist.

**Comment by frankgiordano** [comment]
Closing this issue. Thanks!
