### ISSUE TITLE
Schema doesn't update when installing new plugin

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#1059]
**Current Behavior:**
* Run `zowe config init` in fresh Zowe CLI install without any plug-ins
* Install a CLI plug-in (e.g., @zowe/cics-for-zowe-cli)
* Edit the `zowe.config.json` file in an editor with JSON Schema IntelliSense (e.g., VS Code)
* Attempt to add a new profile with `"type": "cics"`
* IntelliSense thinks the profile type is invalid and won't provide autocompletion for it

**Expected Behavior:** The schema should automatically update to support the profile type of a newly installed plug-in.

**Comment by zFernand0** [comment]
Estimate: 5 - 8 points

Notes:
- Pre-req:  https://github.com/zowe/imperative/pull/635
  - We may need this PR since it could simplify the logic required to implement these updates.
- This `update-schemas` mechanism will be executed after a successful installation and validation of a plugin.
- Don't `update-schemas` if there was an installation error
  - We get this for free
- Don't update schemas if there was a validation error
  - We may need to duplicate logic from the pre-req

What schemas should be updated?
- Any schema found in the existing layers
  - This could include global and user config as long as they exists.
- [Optional] All schemas found in the folder tree
  - Current directory (`./`), `../`, `../../`, ... , `/`

**Comment by jelaplan** [comment]
Could we deliver a schema that has details for all the plugin out-of-the-box? Or allow a user to pick which services to configure when using the init command independent of what plugins are installed? We have another story to create a version of CLI web help that can show details for all plugins accessible from Zowe.org. Relying on interrogating plugins for details like syntax details and config details leaves us vulnerable to these gaps in what folks have already installed. In the case of web help, that comprehensive view will only be available to the person who goes to Zowe.org and not from the zowe web help command which is the more ready avenue.

**Comment by MikeBauerCA** [comment]
For schema, I think going through the long list of services would be tedious and just including all known services in `zowe config init` would make the `zowe.config.json` unnecessarily complex in most cases. Also, including everything in the schema could result in unnecessarily long intellisense selections while editing the config.

For web help, it would be nice to have an option in the CLI that allowed someone to see all web-help even beyond what they had installed to learn what is available. To avoid packaging / generation complexities, perhaps the command could attempt to open the web-help on zowe.org. We just need to be careful with URLs and ensure they won't change frequently. We could continue this part of the discussion on #1080

**Comment by MikeBauerCA** [comment]
Update based on our discussion: `zowe plugins install` command will just update global schema.

To handle project-level schema, `zowe config update-schema` will accept a `--depth` flag that will have a default value of 0. The `--depth` flag will influence how many directories to look down for `zowe.schema.json` files (0 means just search the current directory). The command will always look up the directory structure for `zowe.schema.json` files.
