### ISSUE TITLE
[next]: Remove `plugins` array from config.json

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1071]
In the event that we cannot implement a good transition plan from the old [Plugin Management Facility](https://github.com/zowe/imperative/blob/master/packages/imperative/src/plugins/PluginManagementFacility.ts) to [ConfigPlugins API](https://github.com/zowe/imperative/blob/next/packages/config/src/api/ConfigPlugins.ts), we may need to remove the plugins array from the config.json file generated.

**Comment by t1m0thyj** [comment]
The plugins array has limited functionality already working - if you install CLI plugins into your project's node_modules and manually add them to the plugins array, then Zowe CLI `@next` will load them 🙂 

So far this has been kind of an undocumented "easter egg" and nothing we officially support - so if we decide to remove the plugins array for now, I don't have any objection to that.

Perhaps another option would be to make the plugins array optional, so that it wouldn't be included in any config templates, but users could still add it if they want?

**Comment by zFernand0** [comment]
I think I rather go with the approach of make them (`plugins` and `overrides`) optional instead of removing them! 😋

**Comment by gejohnston** [comment]
Size = 3

- Make the plugins array optional
- Fix any logic that relies on at least an empty plugins array existing.
- Most of the work might be fixing tests that become broken.
