### ISSUE TITLE
Extend zowe files copy data-set command to allow for copying across LPARs / z/OSMF instances

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1098]
Currently, the `zowe files copy data-set` command is useful for easily copying data-sets on the mainframe. However, you may need to copy a data-set across LPARs. Today, you would need to download then upload using the local workstation as an intermediary. This approach may be okay "behind the scenes" but should be transparent to the end user.

**Comment by JTonda** [comment]
When copying datasets, ensure that the DCB information is retained.

Note:  Check to see if target dataset exists.  If exists, check to see if DCB info matches that of source.  If not, stop.  If yes, then we would proceed with copy (download upload).

If target dataset does not exist, then create (with same DCB info as source) and download upload.
If we fail on upload and we had created the target, we would clean up that target.

Also may need to consider the .zosattributes file.  May want to see if direct file transfer is possible instead of using local workstation as intermediary.  If we use the workstation as an intermediary, investigate file streaming.  Investigate using binary/record download upload.  Discussion ongoing.

**Comment by awharn** [comment]
Suggestion if we do need to use a local workstation as an intermediary (this is just a suggestion in the dark, might not be the best idea):
1) Read the DCB
2) Attempt to allocate the new dataset with that DCB
3) Stream in record format
