### ISSUE TITLE
error: Cannot autolaunch D-Bus without X11 $DISPLAY

### ISSUE THREAD

**Issue by tcherkassov** [zowe/zowe-cli#1139]
I'm trying to install Zowe CLI on WSL Ubuntu and running to the issue with creating profile.
Here is an example of command and error (same result in Powershell and in bash terminal in VS Code):
_zowe profiles create zosmf-profile alexei1 --host xxx --port xxxx --user xxx --password xxxx --reject-unauthorized false
Unable to store the secure field "user" associated with the profile "xxx" of type "zosmf".
Error Details:
Cannot autolaunch D-Bus without X11 $DISPLAY_

**Comment by dkelosky** [comment]
i think dbus comes into play because of keytar.  keytar is related to our secure credential store (SCS) plugin.

i was able to reproduce `Cannot autolaunch D-Bus without X11 $DISPLAY` in WSL.   i tried to follow the steps [here](https://github.com/zowe/zowe-cli-scs-plugin#linux-headless), but they didnot work for me.

instead i ran:
1. `sudo apt-get install dbus-x11 gnome-keyring libsecret-1-0`
2. `echo <your-WSL-user-password-here> | gnome-keyring-daemon -d --unlock --login`

then i could create a profile.

however, after i closed WSL and relaunched, i'm getting:

```
** Message: 15:26:49.177: Remote error from secret service: org.freedesktop.Secret.Error.IsLocked: Cannot create an item in a locked collection
Command Error:
Unable to store the secure field "user" associated with the profile "test1" of type "zosmf".
Error Details:
Cannot create an item in a locked collection
```

this will take more time to figure out

**Comment by Simnbf** [comment]
Hi @tcherkassov did you get any further with this? I have the same error message but in a rhel server.

**Comment by aviVzm05** [comment]
Am trying to create zosmf profile in WSL environment. I was able to create the profiles  when secure credential manager is not in effect. However, with scs.... am getting an error like below.

I've followed the processes above..but seems like am missing something here. anyone faced similar error.

zowe profiles create zosmf avinashZosmf --host 192.86.32.67 --port 10443 --user z40728 --password ************* --reject-unauthorized false
Command Error:
Unable to store the secure field "user" associated with the profile "avinashZosmf" of type "zosmf".
Error Details:
No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login

**Comment by t1m0thyj** [comment]
@aviVzm05 This error message indicates that the keyring is still locked. The steps documented in the SCS readme [to automatically unlock the Gnome keyring at log on](https://github.com/zowe/zowe-cli-scs-plugin#linux-headless) only work for Linux systems that you log in to with a password over SSH or TTY. Since WSL automatically logs in without prompting for a password, it is not possible to auto-unlock the keyring with PAM as described in those instructions.

Could you try to manually unlock the keyring with these commands:
```
export $(dbus-launch)
gnome-keyring-daemon --unlock --components=secrets
```

The second command will prompt for your password. Press Ctrl+D twice when you have finished typing it. After this, the keyring should be unlocked and `zowe profiles create` commands should work.

**Comment by aviVzm05** [comment]
@t1m0thyj Thank you... this worked perfectly now. :)

`
avinash@Avinash:/mnt/c/Users/Avinash$ export $(dbus-launch)
Failed to enable unit, unit dbus-daemon.service does not exist.
avinash@Avinash:/mnt/c/Users/Avinash$ gnome-keyring-daemon -r --unlock --components=secrets
avinash** Message: 11:38:40.641: Could not find daemon to replace, staring normally
GNOME_KEYRING_CONTROL=/home/avinash/.cache/keyring-C8MAJ1
avinash@Avinash:/mnt/c/Users/Avinash$ zowe profiles create zosmf avizosmf --host 192.86.32.67 --port 10443 --user z40728 --password ************ --reject-unauthorized false
Profile created successfully! Path:
/home/avinash/.zowe/profiles/zosmf/avizosmf.yaml

host:               192.86.32.67
port:               10443
user:               managed by @zowe/secure-credential-store-for-zowe-cli
password:           managed by @zowe/secure-credential-store-for-zowe-cli
rejectUnauthorized: false
protocol:           https

Review the created profile and edit if necessary using the profile update command.
avinash@Avinash:/mnt/c/Users/Avinash$ zowe scs update
Profile ("avinashDb2" of type "db2") successfully written: /home/avinash/.zowe/profiles/db2/avinashDb2.yaml
Profile ("avinash" of type "zosmf") successfully written: /home/avinash/.zowe/profiles/zosmf/avinash.yaml
Profile ("avizosmf of type "zosmf") was already secure
`

**Comment by pablocarle** [comment]
I see this instructions https://github.com/zowe/zowe-cli-scs-plugin/blob/master/README.md#linux-headless but performing all these steps automatically is not an easy task

**Comment by MikeBauerCA** [comment]
@pablocarle are you trying to store user/password in a profile as part of the pipeline automation? Are you using team config (zowe.config.json)?

Typically in pipeline automation use cases, I recommend leveraging the CI tool's built-in secrets manager. For Jenkins, more info is available at https://www.jenkins.io/doc/book/using/using-credentials/. Then you can access the creds using env vars. Zowe CLI respects specially named env vars like ZOWE_OPT_USER & ZOWE_OPT_PASSWORD.

More details on env var usage related to Zowe CLI is documented here - https://docs.zowe.org/stable/user-guide/cli-usingcli/#using-environment-variables

**Comment by t1m0thyj** [comment]
Closing since this issue has been inactive for a while and a solution was provided - follow the instructions [here](https://github.com/zowe/zowe-cli-scs-plugin/blob/master/README.md#linux-headless), or when possible use your CI tool's built-in secrets manager.
