### ISSUE TITLE
Provide a CLI command to change a job class 

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-cli#1156]
z/OSMF REST API supports changing the job class

https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-change-job-class

A customer asked for this to be available as a CLI command.  Their scenario was to run a job with MSGCLASS=H (held output) then release it to MSGCLAS A.  Sample CLI command could be something like `zowe jobs msgclass change -jobName XXXXXXXX -jobID XXXXXXXX -msgClass XXXXXXXX`

**Comment by zFernand0** [comment]
Should we change verb around? 
Quick suggestion: `zowe jobs change [msgclass | class]`

**Comment by ATorrise** [comment]
It appears [zOSMF ](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-change-job-class)does not allow for changing the msgclass and only class can be changed. What if we were to instead offer an alternative way of [holding](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-hold-job)/[releasing a job ](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-release-job) along with the ability to change class category. 

@zFernand0

**Comment by Joe-Winchester** [comment]
Hi @ATorrise , an alternative way could work.  What is the sort of syntax you're suggesting ?

**Comment by ATorrise** [comment]
Hi @Joe-Winchester, since zOSMF doesn't support the changing of msgclass property, would it be helpful to instead manage the delayed processing of a job via this [hold](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-hold-job)/[release](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-release-job) mechanism?
</br>
I imagine the commands would look similar to what Fernando suggested:

> `zowe jobs manage holdStatus ["release"|"hold"]`
> and
> `zowe jobs manage class ["A"|"B"...]`

Where holdStatus would be defaulted to "release" rather than "hold"
</br>
For this idea, would you prefer the hold property to be a boolean?
> `zowe jobs manage hold [True|False] `

Where the default value is false

**Comment by Joe-Winchester** [comment]
Hi @ATorrise ,  sorry for the late reply.  I really like this design !!!
