### ISSUE TITLE
Create a command to enable daemon mode

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1176]
Create a command to enable daemon mode - perhaps `zowe config daemon`. Overall goal is to install the CLI and simply run a command to enable daemon mode. Daemon mode will initially be off due to the possibility of CLI running in an environment where daemon mode is not supported.

This issue will also include adding documentation for setting up daemon mode.

**Comment by zFernand0** [comment]
Prereqs: 
- Include binaries in CLI tgz #1175 
- next-zowex-is-zowe PR #1114 

Steps:
- [ ] Get OS information
- [ ] Identify which binary to use (from the included binaries)
  a. Output a message with next steps if we can't find a suitable
- [ ] Unzip 
  a. Verify if we have write permissions to the desired path
  b. Unzip to the CLI's node_modules (`process.env.ZOWE_CLI_HOME/_bin` or `~/.zowe/_bin`)
  c. Output a message with next steps if we failed unzip or don't have write permissions
- [ ] Inform the user they need to Update their `$PATH`
- [ ] (Stretch) Attempt to update `$PATH` 
  a. Research how to permanently add the `~/.zowe/_bin` location to the path
  b. Verify if we already added it (to avoid duplication)
  c. Add the `~/.zowe/_bin` location to the path before `$(which zowe)`
  d. Output a message with the next steps if we failed to add the location to the path

Questions:
- [ ] Should `zowe config daemon` be a command **_group_** or just a command?

**Comment by zFernand0** [comment]
> Should `zowe config daemon` be a command **_group_** or just a command?

After some discussion, we will be going with `zowe config daemon`.
A small document will be written with details about the different possibilities and future features of this command. 
Possible options based on Daemon operations:
- Enable:
  - `zowe config daemon` 
  - `zowe config daemon --enable` 
  - `zowe config daemon --disable false` 
  - `zowe config daemon true` 
- Disable:
  - `zowe config daemon --disable` 
  - `zowe config daemon --no-enable` 
  - `zowe config daemon false`
- Refresh:
  - `zowe config daemon --restart`
  - `zowe config daemon --refresh`
  - `zowe config daemon --refresh-plugins`
  - `zowe config daemon-restart`
  - `zowe config daemon-refresh`

Other operations:

**Comment by awharn** [comment]
Right now, I believe our binaries are created for x86 versions of Windows, Linux, and MacOS. We may be able to use `process.platform` to check for `win32`, `linux`, and `darwin`, respectively. There are other platforms, but we don't have any binaries for them.

Then we can check `process.arch` and verify it is `x64` (and maybe `x32` if we know we work on the x86 architecture and deem it high enough priority - 4GB of RAM isn't a lot nowadays) and install the proper prebuilt binary.

As for the stretch of updating the user's path, we might want to reconsider, because that process is going to be very OS dependent, and if done incorrectly, we may end up causing more harm than good.

**Comment by MikeBauerCA** [comment]
I wanted to document here that we had decided to create a new `zowe daemon` group to house these commands. This was due to the likelihood of there being more than two commands created and that the `zowe config` group is currently focused only on team config.

**Comment by gejohnston** [comment]
Resolved by PR  "Next daemon enable for new pipeline" #1251
