### ISSUE TITLE
Daemon Mode tests for rust binary on Windows, Linux, Mac

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1177]
Create a separate set of automated sanity tests for the rust binary on Windows, Linux, Mac.

**Comment by zFernand0** [comment]
Here is a quick Q&A discussed with @t1m0thyj and @awharn 😋 

1. Do we have to build the linux binary in a container?
  a. Option A: Do a simple build from `ubuntu-latest` for testing purposes
  b. Option B: Create a `pre-build` job and upload the linux artifact. Then download it from the `runs-on: {{ matrix.os }}`
  
2. Should the testing matrix be a bit more complex and include npm versions (6.x and 8.x)?
  a. Probably not since that will make the build have twice as many runners for every push
  
3. Should we remove the npm@7 installation from the CI pipeline?
  a. Yes, at least replace it with NPM 8.x
  b. Another alternative is to use the version of npm that comes with NodeJS

Prereq:
- [ ] `zowe config daemon` #1176 (probably)
