### ISSUE TITLE
Daemon Mode - Test/fix changing current directory when multiple requests come in simultaneously

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#1180]
Test and fix changing current directory (and process environment) when multiple requests come in simultaneously.

**Comment by t1m0thyj** [comment]
Resolved in #1317 and #1322. Interleaved requests are now queued (see https://github.com/zowe/zowe-cli/issues/1178#issuecomment-1065194587). This should eliminate any race conditions related to accessing current directory and environment variables in command handlers. Additionally, we stopped recommending use of `process.stdin` (use `IHandlerParameters.stdin` instead) since it only supports a one-time read operation. If we decide to support multithreaded concurrent requests in the future, we will need to revisit how we handle these things.
