### ISSUE TITLE
Daemon fails with space in path on MacOs

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-cli#1237]
From Joe Winchester:

When I had a space in the directory name containing the zowe executable it failed trying to do a chdir command so that may be because the directory name isn't escaped.

**Comment by t1m0thyj** [comment]
@Joe-Winchester Both this issue and the "Socket is not connected" error should be fixed in the latest `@zowe/cli@next` ([7.0.0-next.202112201801](https://www.npmjs.com/package/@zowe/cli/v/7.0.0-next.202112201801)) and daemon binary ([0.4.2](https://github.com/zowe/zowe-cli/releases/tag/native-v0.4.2)). Please let us know if you encounter further issues 🙂
