### ISSUE TITLE
Brightside slow

### ISSUE THREAD

**Issue by kpulver** [zowe/zowe-cli#126]
Why is Brightside so slow? I type bright with no operands and it takes several seconds to respond. It's only help, it should be instant.

**Comment by ChrisBoehmCA** [comment]
Thanks for reporting this and sorry for the issue.  We have this issue to track performance concerns of Imperative CLIs in general 
https://github.com/zowe/imperative/issues/82

It will likely never be instant (it takes some time to start up Node.js and read all the files in the CLI) but we hope to improve the performance

**Comment by AHumanFromCA** [comment]
We are also working on adding some performance metrics to Zowe CLI and Imperative so that we can gather metrics on specific parts of the application.

It's been hard for us to narrow down these issues, some machines spawn the command quickly (less than a second) while others seem to take unreasonable amounts of time (10 plus seconds). For example on my machine, base zowe cli takes approx 1776ms to display `zowe --help` but sometimes it takes over 3000 ms when nothing has been installed or changed.

Our current hunch is that disk operations is where our issues lie and we are working towards tools that will gather and save performance results. When we get that into zowe cli, would you be willing to enable the gathering metrics for us, @kpulver?

**Comment by tucker01** [comment]
Hi @kpulver, do you consistently experience slow response? If you have the "time" bin available to you, you can test with `time zowe`. Try repeating the command a few times to see the results. 

Without all the details, the V8 engine does have JIT and caching mechanisms: 

https://v8.dev/blog/code-caching 

Most folks who issue `zowe` will experience a first time delay (which may again occur periodically, depending on the caching strategy of V8). Usually subsequent commands are much faster. 

We are actively investigating performance of the CLI and looking for improvements.

**Comment by MikeBauerCA** [comment]
Our beta [daemon mode](https://medium.com/zowe/zowe-cli-daemon-mode-29c0dc29c22f) functionality should resolve the performance issue.
