### ISSUE TITLE
`zowe tso issue command` does not always capture SYSUDUMP

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#129]
To reproduce, create a CLIST to invoke an assembler program with a forced abend (e.g. S0C3).  For example, a data set `KELDA16.PUBLIC.JCL(ABEND)` with contents like this:
```
PROC 0                                   
CALL 'KELDA16.PUBLIC.LOADLIB(ASMTEST1)'
```

Invoke the CLIST through zowe CLI via:;
`zowe tso issue command`

SYSUDUMP DD and content does not always appear on the TSO address space.

**Comment by PeteSwauger** [comment]
The behavior is the same if you logon to the system and from the 'READY' prompt execute the clist that executes the program that issues a S0C3.  The SYSUDUMP is only created when executing the clist under ISPF.

From READY:

exec 'swawi03.clist(abend1)'           
 HELLO, WORLD!                         
 IKJ56641I ASMTEST2 ENDED DUE TO ERROR+
 READY                         

From ISPF:
HELLO, WORLD!                                    
IEA995I SYMPTOM DUMP OUTPUT                      
SYSTEM COMPLETION CODE=0C3  REASON CODE=00000003 
  TIME=10.32.47  SEQ=00387  CPU=0000  ASID=0051                         
  PSW AT TIME OF ERROR  078D0000   89F4A510  ILC 6  INTC 03             
    ACTIVE MODULE           ADDRESS=00000000_09F4A4E8  OFFSET=00000028  
    NAME=ASMTEST2                                                       
    DATA AT PSW  09F4A50A - C6000000  0000C0C0  000002B0                
    AR/GR 0: 00000000/00000000_00000000   1: 00000000/00000000_000959A4 
          2: FFFFFFFF/FFFFFFFF_00095820   3: FFFFFFFF/FFFFFFFF_00099F00 
          4: FFFFFFFF/FFFFFFFF_00095F04   5: FFFFFFFF/FFFFFFFF_00095964 
          6: FFFFFFFF/FFFFFFFF_00000000   7: FFFFFFFF/FFFFFFFF_000959A8 
          8: FFFFFFFF/FFFFFFFF_00000000   9: FFFFFFFF/FFFFFFFF_0007E018 
          A: FFFFFFFF/FFFFFFFF_00095610   B: FFFFFFFF/FFFFFFFF_00096FFF 
          C: FFFFFFFF/FFFFFFFF_00096000   D: FFFFFFFF/00000000_000954E0 
          E: 00000000/00000000_00FD8CA0   F: 00000000/00000000_89F4A4E8 
  END OF SYMPTOM DUMP                                                   
 Abend 0C3000 hex occurred processing command 'CALL    '.               
 ISPD210  CMD abended - 'EXEC' terminated abnormally.

**Comment by dkelosky** [comment]
Perhaps its a similar symptom.  I still get a `SYSUDUMP` from the `READY` prompt in my case:
```
                   J E S 2  J O B  L O G  --  S Y S T E M xxxx   --  N O D E xxxxxxxx
                                                                                                
09.55.55 TSU44770 ---- THURSDAY,  28 FEB 2019 ----                                              
09.55.55 TSU44770  $HASP373 xxxxxxx STARTED                                                    
09.55.55 TSU44770  IEF125I xxxxxxx - LOGGED ON - TIME=09.55.55                                  
09.56.15 TSU44770  IEA995I SYMPTOM DUMP OUTPUT  023                                             
   023             SYSTEM COMPLETION CODE=0C1  REASON CODE=00000001                             
   023              TIME=09.56.06  SEQ=42703  CPU=0000  ASID=01AB                               
   023              PSW AT TIME OF ERROR  078D0000   B6F4A236  ILC 2  INTC 01                   
   023                ACTIVE MODULE           ADDRESS=00000000_36F4A210  OFFSET=00000026        
   023                NAME=ASMTEST1                                                             
   023                DATA AT PSW  36F4A230 - D00C0AC7  C0C00000  02C29A0F                      
   023                AR/GR 0: 00000000/00000000_00000004   1: 00000000/00000000_0000CCF0       
   023                      2: FFFFFFFF/FFFFFFFF_0000CDFC   3: FFFFFFFF/FFFFFFFF_0000C768       
   023                      4: FFFFFFFF/FFFFFFFF_8CECE02C   5: FFFFFFFF/FFFFFFFF_007BE940       
   023                      6: FFFFFFFF/FFFFFFFF_0000C970   7: FFFFFFFF/FFFFFFFF_0000C728       
   023                      8: FFFFFFFF/FFFFFFFF_007BE940   9: FFFFFFFF/FFFFFFFF_00FD9678       
   023                      A: FFFFFFFF/FFFFFFFF_8CEDC030   B: FFFFFFFF/FFFFFFFF_0CEDD02F       
   023                      C: FFFFFFFF/FFFFFFFF_0000F098   D: FFFFFFFF/00000000_00010000       
   023                      E: 00000000/00000000_80FD96C8   F: 00000000/00000000_B6F4A210       
   023              END OF SYMPTOM DUMP                                                         
09.56.18 TSU44770  GSVX907I (ISPF.xxxxxxx) SYSVIEW session started, xxxxxxx ISPF A01TD007       
09.56.34 TSU44770  GSVX014I (ISPF.xxxxxxx) xxxxxxx entered command JJCL ,44770                  
```

Here I have the S0C3 prior to getting into SYSVIEW and ISPF.  My SYSUDUMP is captured.

**Comment by PeteSwauger** [comment]
Unable to figure out why no SYSUDUMP when at READY prompt. Reached out to Chuck Kalish and Suzane Diez for their expertise

**Comment by PeteSwauger** [comment]
Chuck responded that the ENTER key needs to be pressed without any other input to generate the dump.  Looking at how to send a null value via zowe to generate the dump.

**Comment by PeteSwauger** [comment]
In order to have the abend generated TSO requires the ENTER key to be pressed with no text input.  This is not possible with 'zowe tso issue' as it generates a unique TSO address space each times it's executed.  The answer is to start a TSO address space, send the command, check for failure and send a 'blank' (" ") command to generate the abend.

$ zowe zos-tso start address-space --sko                                                    
<userid>-96-aabyaaai                                                                         
                                                                                                                                                  
$ zowe zos-tso send address-space <userid>-96-aabyaaai --data "exec '<userid>.clist(abend1)'" 
HELLO, WORLD!                                                                               
IKJ56641I ASMTEST2 ENDED DUE TO ERROR+                                                      
READY                                                                                       
                                                                                            
$ zowe zos-tso send address-space <userid>-96-aabyaaai --data " "                            
IEA995I SYMPTOM DUMP OUTPUT                                                                 
SYSTEM COMPLETION CODE=0C3  REASON CODE=00000003                                            
 TIME=13.36.28  SEQ=01432  CPU=0000  ASID=0060                                              
 PSW AT TIME OF ERROR  078D0000   89F4A510  ILC 6  INTC 03                                  
   ACTIVE MODULE           ADDRESS=00000000_09F4A4E8  OFFSET=00000028                       
   NAME=ASMTEST2                                                                            
   DATA AT PSW  09F4A50A - C6000000  0000C0C0  000002B0                                     
   AR/GR 0: 00000000/00000000_00000004   1: 00000000/00000000_0000ACF0                      
         2: FFFFFFFF/FFFFFFFF_0000ADFC   3: FFFFFFFF/FFFFFFFF_0000A768                      
         4: FFFFFFFF/FFFFFFFF_848DD02C   5: FFFFFFFF/FFFFFFFF_007D3940                      
         6: FFFFFFFF/FFFFFFFF_0000A970   7: FFFFFFFF/FFFFFFFF_0000A728                      
         8: FFFFFFFF/FFFFFFFF_007D3940   9: FFFFFFFF/FFFFFFFF_00FD8C50                      
         A: FFFFFFFF/FFFFFFFF_848EB030   B: FFFFFFFF/FFFFFFFF_048EC02F                      
         C: FFFFFFFF/FFFFFFFF_0000D4A8   D: FFFFFFFF/00000000_0000EF68                      
         E: 00000000/00000000_80FD8CA0   F: 00000000/00000000_89F4A4E8                      
 END OF SYMPTOM DUMP                                                                        
READY  

$ zowe zos-tso stop as <userid>-96-aabyaaai
TSO address space ended successfully, key was: <userid>-96-aabyaaai

==========================================================================

The JES output shows the SYSUDUMP DD

JobName  JobId     Queue    Datasets     Lines  ExecSys                                                                            
<userid>  TSU06687  EXECUTE         4     13369  DE20                                                                               
----------------------------------------------------------------------
Cmd      DDname   Stepname Procstep Status     Cpys  TotLines OutClass  
________ JESMSGLG JES2              OPEN                                           2  Z   
________ JESJCL   JES2                                                   1                  18  Z    
________ JESYSMSG JES2              OPEN                                            2  Z  
________ SYSUDUMP PROCxxx  PROCxxx                1           13347  A

**Comment by dkelosky** [comment]
Thanks for all your research on this.  It's good to know specific steps to get intended results.  I'll close
