### ISSUE TITLE
Change the phrase 'deprecated' to indicate to users the profiles are still supported in v2 and also relevant in many user cases

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-cli#1324]
v2 supports configuration data being held in profiles as well as configuration files.

```
Warning: The command 'profiles list' is deprecated.
Recommended replacement: The 'config list' command
```

For users (in DevOps scenarios) team configuration files is a good option to collaborate.
For other users in system programmer scenarios profiles is still a good choice to operate.  

Doing demos to users recently they have complained about the use of the word `deprecated`.  This implies to them that they need to migrate to use config files, however I am having to explain to users that profiles are still OK to use.  The suggestion is to remove the message about `profiles` commands being deprecated, as this implies that they no longer work or are less functional, rather than it being a user choice for how they want to manage their configuration information

**Comment by MikeBauerCA** [comment]
@Joe-Winchester we had listed them as deprecated as we would like to move away from the old profile format in Zowe V3 LTS. If you have concerns about that, let's set up a call. Thanks for raising this point prior to the release date 👍

**Comment by Joe-Winchester** [comment]
@MikeBauerCA ,  I think a call would be good.  Would you prefer this was a specific topic call, or occurred during one of the regular CLI squad weekly calls ?  What I'm hearing is that while `zowe.config.json` works well in the scenarios it was designed for,  not having commands like `zowe config list <type>` or having to update team config properties value by value (rather than the `zowe profiles update --name1 value1 --name2 value2 --name3 value3`).

**Comment by BJostmeyer** [comment]
Maybe I still misunderstand the concept of config - sorry, I have not played with this yet. 
However, as far I understand config is great if a bigger team of developer/operator want to access the same system and dont want to deal with setting up the same connections.

However - in a DevOps environment different operator use different systems for their purpose - and sometimes even do not share systems/environments - just in order to test their personal recent changes to their product. In this case they have own profiles like (DEV_Issue#1234) or something like this. So, I think having profiles is perfect in this case.

I compare profiles to the connections I have saved in a tool similar like "putty", which I am using on Windows to connect to and manage my connections to different systems. Those connections (and the passwords / keys) stored inside are my private ones.

So - I thought that config & profiles both have their scenarios and will both stay even in future?

**Comment by gejohnston** [comment]
Here are a few comments for clarification (not meant to resolve this issue).

The CLI team definitely meant for the term "deprecated" to imply that the old-school profiles will go away. We are supporting them in V2 to provide ample opportunity for users to migrate to the V2 team configuration.

Some comments implied that team config can only be used in scenarios in which the configuration is to be shared with others. When created with the --global option, the team config's scope will be the same as the old-school profiles. The user can also keep that team config all to himself.

When casual changes are required, we advocate just changing the zowe.config.json file in your favorite text editor. If such changes are to be automated, we created the 'zowe config set' command to enable users to set values by issuing multiple 'set' commands in a script. If these mechanisms do not properly address required use-cases, I would advocate pursuing an enhancement to address additional needs, rather than retaining the old-school profiles in V3 and later.

**Comment by gejohnston** [comment]
Since the deprecation and eventual remove of V1 profiles were always a planned evolution of the Zowe CLI, I am closing this issue.

If the 'zowe config set' command cannot accomplish your desired automation, we encourage you to open an enhancement request against that command group.
