### ISSUE TITLE
With Zowe V2 using "convert-profiles" removes encryption of stored passwords

### ISSUE THREAD

**Issue by BJostmeyer** [zowe/zowe-cli#1330]
Hi,
I installed the current version of Zowe CLI, which sooner or later will become V2 LTS. So far I was using V1 and had for my "SA" plugin around 10 profiles created - all contained an encrypted password.

Now I installed V2 and migrated the plug-ins - which removed the secure credential store plug-in. Also I used "zowe config migrate-profiles" to see what happens:

1. The old .zowe/profiles/sa folder is renamed to .zowe/profiles-old/sa folder with the old yaml files inside which used to be my profiles. However - and this I have a strong issue with - the passwords which used to be encrypted are now stored readable as plain text! 
I have not really a problem when using migrate-profiles I have this renamed folder - however passwords should rather be removed then stay now as clear text in a file ! This violates security rules in (I guess) any organization not to have clear text passwords - even if the files are not actively being used anymore...

2. After I did the migrate-profiles step I am unable to create new ones. I get an IO Error !?! I mean if the step "migrate-profiles" is ir-reversable I should be warned about this fact ("Do you really want to?") when I am doing this - and get a good message when I try to create a new profile that says something like "You are not allowed to create profiles anymore, since you migrated to config" or something like this - instead of an IO Error. 
However - I still think that having profiles and/or config should stay possible in future - but this is another issue...

**Comment by Joe-Winchester** [comment]
Thanks @BJostmeyer ,  to me this seems like a vulnerability, as what you're describing is the scenario
- I am a v1 users with `/profiles` that are using SCS
- I migrate to the team config in v2, and the userId and passwords are read from SCS and put into the `zowe.config.json` file in plain text.
The behavior I would have expected is
- I migrate to the team config in v2 and the user and password in the `/profiles` SCS are migrated and kept secure
- or,  if the above can't occur, then the SCS credentials are not taken out of SCS and put into clear text by default.  If as a user I want this behavior that could be a `--expose-credentials` argument so it's an explicit wish.

**Comment by BJostmeyer** [comment]
Hi @Joe-Winchester - i was only looking at the files in the new directory "profiles-old", but yes - you are right even in "zowe.config.json" they are in Plain-text !!!!

![image](https://user-images.githubusercontent.com/36626099/156751287-f928bb23-a642-4cdb-b9b0-28d608cf4773.png)

**Comment by BJostmeyer** [comment]
I would not offer an argument <--expose-credentials>.  In all good practice - under NO circumstances passwords should ever stored readable in a text file! 

Even if a customer would choose to specify this parameter - that is a violation against any good security practice - and therefore not offer this feature.

**Comment by gejohnston** [comment]
We conducted the same scenarios described in this issue and found no behavior in which the 'config migrate-profiles' command altered securely-stored credentials into plain-text credentials.

We used the current Zowe CLI V1-LTS GA version (6.40.7) to create working profiles for z/osmf and several plugins.
- We created a set of profiles with plain-text creds.
- We created a second set of profiles with securely-stored creds.
- We created a third set of profiles by running 'scs revert' on profiles that contained securely-stored creds. The result was a set of profiles with plain-text creds. The resulting profiles were identical to the original set of plain-text credentials. 

We upgraded to the current Zowe CLI V2-LTS GA version (7.5.1).

We ran the 'config migrate-profiles' command against the profiles with securely-stored creds. After resetting, we ran the 'config migrate-profiles' command against the profiles with plain-text creds.

In all cases, the contents in profiles-old were identical to the original profiles.
- When the original profiles contained securely-stored credentials, they remained marked as 'managed by @zowe/secure-credential-store-for-zowe-cli' in profiles-old.
- When the original profiles contained plain-text credentials, profiles-old contained the same plain-text credentials.

The resulting zowe.config.json file demonstrated similar results.
- When the original profiles contained securely-stored credentials, zowe.config.json contained no credentials. It contains empty 'secure' arrays. It also contains the 'autostore: true' property. When a user runs a command that requires credentials, the user is prompted for the creds. Those creds are stored in the secure credential store, and the associated 'secure' array is populated with the names of the credentials. On future commands, the user is no longer prompted for the credentials.
- When the original profiles contained plain-text credentials, zowe.config.json contained plain-text credentials. By design, the 'config migrate-profiles' does not alter the user's previous decision to store plain-text creds into forcing securely-stored credentials.

Regarding the second topic on reverting back to V1 profiles, you **CAN** revert to V1 profiles after migrating your V1 profiles into a zowe.conf.json V2 team configuration. You simply cannot use V1 profiles and V2 team configuration at the same time. If you rename or remove your zowe.config.json file, the Zowe CLI 'profiles' commands will issue a warning that the commands are deprecated, but they perform the desired operation. If you rename 'profiles-old' back to 'profiles', Zowe CLI will use your old profiles once again.

All of the re-tested results above are the expected behavior of Zowe CLI. Speculation on why you may have seen the undesireable results that you reported include:
- Perhaps the pre-release version that you used had some misbehavior that no longer exists in the app. We are not aware of any such previous misbehavior, but we cannot rule out that possibility.
- Perhaps while performing a variety of tests, you converted a set of profiles that inadvertently had plain-text creds, but you thought that they contained securely stored creds.
    
Since our tests confirm that all scenarios operate as designed (and as expected), we are closing this issue. We encourage you to re-open this issue, if you can reproduce the misbehavior and can describe the unique conditions which cause such a misbehavior.

**Comment by Joe-Winchester** [comment]
Thanks for the extensive testing @gejohnston .   Security is important to Zowe's customers and I really appreciate the diligence and steps you've taken here to double check that there is no vulnerability in the GA offering.
