### ISSUE TITLE
`zowe auth login apiml` fails in V2 with HTTP status code 405

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-cli#1339]
I am using the last @next version of the Zowe CLI:

```
$ zowe --version                                                                   
7.0.0-next.202203091358
```

with beta version of the Zowe API ML (Version 2.0.4-SNAPSHOT build # n/a).

The command fails:
```
zowe auth login apiml                                                                         
Enter the port number of your service: ******
Command Error:
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 405

Error Details:
HTTP(S) error status "405" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Protocol:  https
Host:      *****.lvn.broadcom.net
Port:      ******
Base Path:
Resource:  /api/v1/gateway/auth/login
Request:   POST
Headers:   undefined
Payload:   undefined
```

**Comment by jguillaumes** [comment]
https://github.com/zowe/vscode-extension-for-zowe/issues/1808 Could be relarted to this.

**Comment by awharn** [comment]
I believe that this issue was meant to be closed when #1360 was merged in. What is the version of the APIML that you are using to log in? A change was made in v2 (and support was backported in v1) that changed the login endpoint from `/api/v1/gateway/auth/login` to `/gateway/api/v1/auth/login`. It is possible that this issue may be because you are using the V2 Zowe CLI with an older V1 API Mediation Layer that does not have support for the new login endpoint URI. 

@balhar-jakub do you have any information about which version of the API Mediation Layer introduced support for the new login URI?

**Comment by balhar-jakub** [comment]
In 1.20.0 https://github.com/zowe/api-layer/blob/v1/CHANGELOG.md#1200-2021-03-11

**Comment by plavjanik** [comment]
Thanks for addressing the issue!
