### ISSUE TITLE
Zowe issue under Git Bash with file-to-uss upload

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/zowe-cli#1383]
Hi,

The files upload file-to-uss command does not work when run from Git Bash for Windows.

The USS path is transformed into a Windows-like path with the reference to a disk.

In the example below `/u/J070188/...` is transformed into `U:/J070188/...` which USS does not understand.

```
$ zowe files upload ftu "c:\Trv\DepotsGIT\environn-techleads-sandbox\src\S9T\COBOL\MINIMAL.cbl" "/u/J070188/vscode/environn-techleads-sandbox/src/S9T/COBOL/MINIMAL.cbl"
Command Error:
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 404
category: 6
rc:       8
reason:   93651005
message:  File not found.
details: 
  - EDC5129I No such file or directory. (errno2=0x0594003D)

Error Details:
HTTP(S) error status "404" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Protocol:  https
Host:      gmvs
Port:      8444
Base Path:
Resource:  /zosmf/restfiles/fs/U%3A%2FJ070188%2Fvscode%2Fenvironn-techleads-sandbox%2Fsrc%2FS9T%2FCOBOL%2FMINIMAL.cbl
Request:   PUT
Headers:   [{"X-IBM-Data-Type":"text;fileEncoding=1147"},{"Accept-Encoding":"gzip"},{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined
```

The same command run from a Windows Command Prompt works:

```
>zowe files upload ftu "c:\Trv\DepotsGIT\environn-techleads-sandbox\src\S9T\COBOL\MINIMAL.cbl" "/u/J070188/vscode/environn-techleads-sandbox/src/S9T/COBOL/MINIMAL.cbl"
success: true
from:    c:\Trv\DepotsGIT\environn-techleads-sandbox\src\S9T\COBOL\MINIMAL.cbl
to:      /u/J070188/vscode/environn-techleads-sandbox/src/S9T/COBOL/MINIMAL.cbl

USS file uploaded successfully.
```

**Comment by t1m0thyj** [comment]
This is an issue with Git Bash where it automatically expands paths before passing them to Zowe CLI. There are 2 workarounds suggested on [StackOverflow](https://stackoverflow.com/questions/7250130/how-to-stop-mingw-and-msys-from-mangling-path-names-given-at-the-command-line):
* Use two leading slashes instead of one at the front of your path (e.g., `//u/J070188/...` instead of `/u/J070188/...`). This stops Git Bash from auto-converting the path, and is accepted by Unix as a valid path.
* Set the environment variable `MSYS_NO_PATHCONV=1` to disable Git Bash auto-converting paths, but this may have undesired side effects if you run Bash scripts (for example, it would break `/tmp` auto-converting to `C:\Users\<username>\AppData\Local\Temp`).

**Comment by FALLAI-Denis** [comment]
Hi @t1m0thyj 

Thanks for the workarounds for the problem.

Am I to understand that the issue is specific to the runtime used by Git Bash (mingw/msys)?

I rather think to adopt the second solution (`MSYS_NO_PATHCONV=1`) because it doesn't seem normal to me to have to adapt the path expression syntax according to the context in which I execute the Zowe file-to-uss command.

**Comment by FALLAI-Denis** [comment]
FYI
- I created a file. bashrc in my C:\users\<user> folder
- at the first launch of git-bash I got an alert:
![image](https://user-images.githubusercontent.com/63861965/165140223-1acb68b8-9992-411c-98f2-bc94638d9dfe.png)
- on the second launch, no alert

I ran the Zowe CLI file-to-uss command again:
![image](https://user-images.githubusercontent.com/63861965/165140768-d09d3317-aac7-4afb-b6d7-7de54ad344b3.png)

Great!

**Comment by t1m0thyj** [comment]
@FALLAI-Denis You are correct, the issue is specific to the runtime used by Git Bash, so not an issue that can be fixed in Zowe CLI. Glad you were able to get it working and thanks for documenting the steps you used, should be useful for anyone else who hits this problem 🙂 Is this issue good to close?

**Comment by FALLAI-Denis** [comment]
Good to close
