### ISSUE TITLE
Zowe files view data-set 

### ISSUE THREAD

**Issue by kraabrsg** [zowe/zowe-cli#1424]
Hi, with 7.2.0 is the output of the files not expected:

![grafik](https://user-images.githubusercontent.com/86772851/168752443-b619a6db-fbea-4978-8e21-7e2393df186d.png)

seems like vb is not treated accordingly...
(the vscode powershell terminal seems to also have an issue here)

**Comment by KevinLoesch1** [comment]
Hi, 

  This is not a problem with variable block files or the view command itself. It is the behavior of the Windows console interpretting a line feed(0x25 EBCDIC) without a corresponding carriage return.  A normal Unix type text file will end each line with a carriage return. When transferring the file to Windows with the ASCII/TEXT conversion enabled this would cause any carriage returns to be converted to a CR/LF. Since the example file provided ends each record with a line feed only, no end-on-line conversion occurs. Windows interprets this line feed only by moving the cursor to the beginning of the current line, then it overwrites the current line with the data that is in the next record. 
  
  
  I was able to create the same behavior inside USS when using a VT type terminal emulator. I copied the sample file to USS, then did a 'cat' against the file. 

![image](https://user-images.githubusercontent.com/102045561/169843133-591317a6-051a-449f-8334-d6d65be09424.png)


If you issue the view command but pipe the data to the file you will also see it that it does not overwrite the each line. For example, if I issue 'zowe files view ds 'USER1.TEST.VB'  > sample.txt' then view the newly created sample.txt in notepad it looks like this:

![image](https://user-images.githubusercontent.com/102045561/169843965-5efb8014-556e-40e2-9dbd-4b3ce8493742.png)


Please confirm that this is the only issue you are seeing with variable block files. If so, I would like to close this issue.

**Comment by KevinLoesch1** [comment]
@[kraabrsg](https://github.com/kraabrsg) 

The conversion I was referring to is the default EBCDIC to ASCII that automatically occurs unless the **--binary** flag is used. 


You can get the same functionality provided by **zowe files view** via the SDK by using the Get class. It has methods for retreiving both USS files and datasets. 
https://github.com/zowe/zowe-cli/blob/master/packages/zosfiles/src/methods/get/Get.ts
