### ISSUE TITLE
The 'zowe config secure' command removes a comment

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-cli#1433]
Zowe version = 7.2.1
OS = windows

- Comment out the rejectUnauthorized property in a base profile.
- Add rejectUnauthorized as a secure property in a zosmf profile.
- Run 'zowe config secure'
- The comment is removed from the base profile.

rejectUnauthorized is not a realistic property to make secure, but I assume other properties would also remove a similar comment. A customer might want the comment left around during testing to remember the previous value (I did).

Example config file:
```
{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "base_secure_pass": {
            "type": "base",
            "properties": {
                // "rejectUnauthorized": false
            },
            "secure": [
                "user",
                "password"
            ]
        },
        "ca32": {
            "type": "zosmf",
            "properties": {
                "host": "usilca32.lvn.broadcom.net",
                "port": 1443,
                "responseFormatHeader": true
            },
            "secure": [
                "rejectUnauthorized"
            ]
        }
    },
    "defaults": {
        "base": "base_secure_pass",
        "zosmf": "ca32"
    },
    "autoStore": false
}
```

> zowe config secure
Enter profiles.base_secure_pass.properties.user - blank to skip:
Enter profiles.base_secure_pass.properties.password - blank to skip:
Enter profiles.ca32.properties.rejectUnauthorized - blank to skip:

The config file is changed as follows:

![image](https://user-images.githubusercontent.com/37119146/171451020-8e9ec802-6e3f-4303-b7d7-2f57b19585ad.png)

**Comment by ATorrise** [comment]
There are 3 possible courses of action here:

1. Adding to documentation that you can't add comments to the profiles section of the config.json file. This is because profiles get merged via a dependency, [deepmerge](https://www.npmjs.com/package/deepmerge-json), that doesn't retain comments in its output. 

2. Removing deepmerge as a dependency and writing our own in-house methods to merge profile information. 

Option 2 is high effort given the situation that no external users have raised a concern about this topic. Option 1 would be the only indication in all of zowe documentation that users can insert comments in their json files, a behavior that is usually not allowed. Because this behavior is unexpected, I don't think alerting users to the intricacies of its use cases is helpful and instead would be confusing. 

3. Close the issue and take no action. 

Because we don't want to confuse our users and we want to address their current concerns, I will be closing this issue.
