### ISSUE TITLE
CLI diff of USS files in terminal/browser

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1445]

**Comment by Rahulkhinchi03** [comment]
Hi @zFernand0,
I'm Rahul Khinchi, applied to the LFX Program at Zowe CLI.

Until then, I am learning ZOWE CLI and would like to work on this issue. In order to understand what enhancements are required for CLI, could you please explain the scope of this issue?

PS: I've read the documentation for Zowe, tested it in my environment, and played with the cli options.

**Comment by zFernand0** [comment]
Hey @Rahulkhinchi03,
It would be amazing if you would like to work on this.
However, I'm afraid that the application process for the LFX Mentorships is already closed and mentees have already been accepted for the various project. You should be hearing back from LFX soon 😋
