### ISSUE TITLE
zowe not found after I installed it on my linux

### ISSUE THREAD

**Issue by RedGoldPhoenix** [zowe/zowe-cli#1494]
Hello 
I did the installation as you can see below

```
 bruno@bruno-Aspire-E5-521:~/Téléchargements/zowe-cli-package-2.2.0$ npm i --location=global zowe-cli.tgz 

changed 22 packages, and audited 309 packages in 55s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
bruno@bruno-Aspire-E5-521:~/Téléchargements/zowe-cli-package-2.2.0$ npm fund
zowe-cli-package-2.2.0
├── https://github.com/sponsors/sindresorhus
│   └── get-stream@6.0.1, p-limit@2.3.0, p-map@4.0.0, decompress-response@6.0.0, mimic-response@3.1.0
├── https://github.com/sponsors/isaacs
│   └── glob@7.1.6, rimraf@3.0.2
├── https://github.com/chalk/wrap-ansi?sponsor=1
│   └── wrap-ansi@7.0.0
├── https://github.com/sponsors/feross
│   └── run-parallel@1.2.0, queue-microtask@1.2.3, simple-get@4.0.1, simple-concat@1.0.1, buffer@5.7.1, base64-js@1.5.1, ieee754@1.2.1
├── https://github.com/sponsors/jonschlinkert
│   └── picomatch@2.3.1
├─┬ https://github.com/chalk/chalk?sponsor=1
│ │ └── chalk@4.1.2
│ └── https://github.com/chalk/ansi-styles?sponsor=1
│     └── ansi-styles@4.3.0, ansi-styles@5.2.0
└── https://github.com/fb55/entities?sponsor=1
    └── entities@2.1.0
```
but when I try to launch the zowe command my Linux doesn't find it
Could you tell me which path I must check or because when I look on the $PATH I have this

`bash: /home/bruno/anaconda3/condabin:/home/bruno/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/bruno/.dotnet/tools `

Last information if one day you have an issue with npm and the error:
npm ERR! code EFUNDGLOBAL 
follow the information below to update files npm.cmd, npm, npx.cmd and npx  
https://stackoverflow.com/questions/72401421/message-npm-warn-config-global-global-local-are-deprecated-use-loc

Thanks a lot for your help

**Comment by gejohnston** [comment]
After completing an NPM installation of Zowe CLI, you can identify the directory containing the Zowe NodeJS command script by running the following command:

    npm prefix -g

I believe that this issue has been resolved through email and other communcation channels, so we will close this issue within the next week.

If this issue is still a problem for you, just add another comment to this issue.

**Comment by RedGoldPhoenix** [comment]
Hello Gene

I ran you command you gave me and you have the result below :
/home/bruno/.npm-global/bin

When I try to go to the folder I can see that Zowe it here
(base) bruno@bruno-Aspire-E5-521:~/.npm-global/bin$ ls -a
.  ..  bright  npm  npx  prebuild-install  zowe

I tried to export variable like export npm_config_global=~/.npm-global/bin 
but zowe is always unknonw ...

any Idea ?

**Comment by RedGoldPhoenix** [comment]
When I go on the folder ~/.npm-global/bin, and I click right to the icon I go read the properties, the target link is ../lib/node_modules/@zowe/cli/lib/main.js
but I don't find it in /usr/lib/node_modules  
that is really strange

**Comment by gejohnston** [comment]
Your original npm installation command specifies a flag "--location=global". I do not believe that npm accepts any such flag. Therefore, I doubt that you got the results that you intended. You should probably run a correct npm install command, before attempting any further actions.

I do not believe that the command "export npm_config_global=~/.npm-global/bin" is meaningful to npm or zowe.

Finally, in the link "../lib/node_modules/@zowe/cli/lib/main.js", the "../" portion points to the parent directory of your current directory, not "/usr".

**Comment by MarkAckert** [comment]
In case this is unresolved...

It sounds like you've configured your global npm install directory to `~/.npm-global/bin`, and the `--location=global` installed the package there. Rather than running `export npm_config_global=~/.npm-global/bin` to make `zowe` available on the command line, I believe you need to run `export PATH=$PATH:~/.npm-global/bin`. 

Since this issue hasn't seen any updates in a few months and there were other communication threads on the topic, I will be closing it. If you disagree you may re-open it. Thank you!
