### ISSUE TITLE
Allow Zowe Daemon Configuration to Use TCP Socket 

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#1536]
I've run into a few intermittent issues that are hard to understand the specifics of when I use zowe daemon with pipes for which tcp didn't cause issues.  @zFernand0, @gejohnston, @t1m0thyj, and others, any objections to drafting this as a PR? It'll take time and will not be the default (likely controlled by env var).  

I understand there were concerns around security on shared systems; however, this plan would be to allow for binding to `localhost` on single user systems.  

Adding #1318

**Comment by dkelosky** [comment]
example infrequent error when running `zowe files view ds` : 

```
I/O error during daemon communication.
Details = The pipe has been ended. (os error 109)
```

**Comment by gejohnston** [comment]
Should the team focus on any fixing bug(s) in the existing communication instead of creating a different communication just to workaround a bug?

**Comment by gejohnston** [comment]
We have observed intermittent errors in the download command with large data sets. We opened an RFE with IBM on this behavior. As a result, we speculate that both the view and download commands can demonstrate this error in both daemon and non-daemon mode. Because of the intermittent nature of the error, it can be difficult to identify which command or environment has the failure. Our current working theory is that it stems from the zosmf transfer of large data sets.

The issues below are also related to errors when a large volume of data is transferred:

- #307
- [IssueTso.issueTsoCommand incomplete response / data loss #690](https://github.com/zowe/zowe-cli/issues/690)
