### ISSUE TITLE
zowe auth login apiml does not update z/OSMF information

### ISSUE THREAD

**Issue by pablocarle** [zowe/zowe-cli#1620]
**Expected and actual results**

According to the instructions here: https://docs.zowe.org/stable/user-guide/cli-using-integrating-apiml/#specifying-a-base-path
After using `zowe auth login apiml` only the basePath needs to be provided, and port removed from the profile definition.
However, port is not added as a property, and with the following configuration, when running `zowe zosmf check status` as an example, it tries to connect directly to the default z/OSMF default port `443`

The expected result should be to update the API ML Gateway port in the base profile as well, or perhaps validate the profile.
As default the port that it tried to reach does not appear in the error message, which is simply a 404, although I could distinguish the path that it was trying to reach.

Adding the port to the base profile in this configuration helped.

Profile config (after running `zowe auth login apiml`:

```json
"lpar-apiml": {
    "properties": {
        "host": "lpar.mydomain"
    },
    "profiles": {
        "base": {
            "type": "base",
            "properties": {
                "tokenType": "apimlAuthenticationToken"
            },
            "secure": [
                "tokenValue"
            ]
        },
        "ssh": {
            "type": "ssh",
            "properties": {
                "port": 22
            }
        },
        "tso": {
            "type": "tso",
            "properties": {
                "account": "tsoaccount"
            }
        },
        "zftp": {
            "type": "zftp",
            "properties": {
                "secure-ftp": false
            }
        },
        "zosmf": {
            "type": "zosmf",
            "properties": {
                
            }
        }
    }
}
```

Expected config (or other alternative):

```json
"lpar-apiml": {
    "properties": {
        "host": "lpar.mydomain"
        "port": <GATEWAY PORT>
    },
    "profiles": {
        "base": {
            "type": "base",
            "properties": {
                "tokenType": "apimlAuthenticationToken"
            },
            "secure": [
                "tokenValue"
            ]
        },
        "ssh": {
            "type": "ssh",
            "properties": {
                "port": 22
            }
        },
        "tso": {
            "type": "tso",
            "properties": {
                "account": "tsoaccount"
            }
        },
        "zftp": {
            "type": "zftp",
            "properties": {
                "secure-ftp": false
            }
        },
        "zosmf": {
            "type": "zosmf",
            "properties": {
                
            }
        }
    }
}
```

**Describe your environment**

- Zowe CLI version installed: 7.10.2
- Installed plug-ins and their version numbers:
- Node.js and NPM versions installed: 
```
@broadcom/endevor-for-zowe-cli@7.0.1
@zowe/zos-ftp-for-zowe-cli@2.0.2
```
- Environment variables in use:
- Operating system and version: MacOS 12.5.1
- Shell/terminal: zsh
- Daemon mode enabled or disabled: disabled

**Comment by pablocarle** [comment]
Also, I opened an issue in docs-site: https://github.com/zowe/docs-site/issues/2629

**Comment by gejohnston** [comment]
The 'zowe auth login' command was not designed to setup your connection to APIML. It logs into a configured connection for APIML (or it prompts for host and port) so that it can obtain an APIML auth token, and store the token for future use.

You can hand-configure the APIML host and port into your base profile before running 'zowe auth login'. 

An alternative is to ask zowe CLI to automatically generate a configuration for you with the 'zowe config auto-init' command. That command will prompt you for the APIML host and port. They will be stored in your generated config file. That command will also automatically perform the APIML login to obtain and store the APIML token into your generated config file. You should then be able to run zowe commands against any service to which APIML dipatches requests.

Since the behavior that you encountered is how these commands were designed, I re-labeled this issue as an enhancement.
