### ISSUE TITLE
Show output of example commands (maybe in help displays/text)

### ISSUE THREAD

**Issue by tucker01** [zowe/zowe-cli#165]
It would be beneficial for users to have the output of example commands to help with understanding the commands purpose and scripting.

**Comment by jelaplan** [comment]
Good idea. Concrete information, such as examples is often easier to understand than abstract descriptions of commands and options. I took a look at GIT and they offer a section on output. For example git status --help.  They explain the output rather than just give an example. 

A complication to adding example output is that it can be verbose and make some long man pages even longer. The Git output stuff is pretty long. 

Again referencing Git, I can type git status --help or git status -h and the former gives me verbose help and the latter gives an abbreviated help. I wonder if we might want to tackle both abbreviated help and longer full help pages?

**Comment by MarkAckert** [comment]
Most of Zowe CLI's commands now come with examples and is the default. If any commands are missing examples, they should be re-opened on a case-by-case basis.
