### ISSUE TITLE
Download and Upload Multiple Files Behavior is Inconsistent 

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#166]
`zowe files download am --help` shows:
```
   --max-concurrent-requests  | --mcr (number)

      Specifies the maximum number of concurrent z/OSMF REST API requests to download
      members. Increasing the value results in faster downloads. However, increasing
      the value increases resource consumption on z/OS and can be prone to errors
      caused by making too many concurrent requests. If the download process
      encounters an error, the following message displays:
      The maximum number of TSO address spaces were created. When you specify 0, Zowe
      CLI attempts to download all members at once without a maximum number of
      concurrent requests.

      Default value: 1
```

So download is done 1 member at a time;  However, `zowe files upload dtp` seems to have no equivalent.  Is this intentional?

**Comment by AHumanFromCA** [comment]
I don't think that upload does concurrent requests. I believe there was some restriction on uploading concurrently because it is a write operation instead of a read operation.

**Comment by dkelosky** [comment]
There are concurrent requests on upload (which is a cool behavior).  But, it seems inconsistent when downloading vs uploading several files at once.

I'm not clear that throttling requests fixes the original error doing too many requests at once, but it probably reduces the chances of it occurring (this seems like its really a z/OSMF issue to deal with).

I'll close this though - my question was answered.  Thanks!

**Comment by AHumanFromCA** [comment]
Yeah, I believe we had a similar discussion about this when we encountered the download problem. Ideally we should be able to send out any number of requests at a time without the remote system bugging out.

We probably wouldn't want to sent out all the requests at once since I'm pretty sure the PC would not be happy with thousands of active requests. If we sent out something like 10 downloads currently, the mainframe should not create 10 user sessions for each request. It should share the session, but hey what are we gonna do right?
