### ISSUE TITLE
Research Secure Storage for Zowe CLI on USS

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1673]
As Zowe developers, we want to understand what options are available so that I can store credentials securely under USS. 

Options:
- Node.js crypto

This issue may be related to:
- #1213

**Comment by Joe-Winchester** [comment]
Has anyone looked at the buttercup package ?   https://github.com/buttercup/buttercup-core.

**Comment by gejohnston** [comment]
@Joe-Winchester - Thanks for identifying Buttercup. I do not think that we were aware of this option.

For the secure storage options that we have encountered so far:

- Creating our own secure vault with NodeJS Crypto
- Keybase's PGP for JavaScript
- Equinox Secure Storage mechanism used by the IBM Installation Manager
- Buttercup

A common characteristic is that they need an initial password to be supplied to kick-off the encryption activities.

Since each new Zowe CLI command starts fresh, we must find a way to retain that password, so that we do not have to ask the user to enter the password on every Zowe CLI command. Identifying an acceptably secure way of retaining that password remains an on-going investigation. We are also keeping our eyes open for a tool that has already created a scheme for safely holding that initial password and is viable on USS.
