### ISSUE TITLE
How to remove a userid/password (SecureArgs ) pair from the Credentials vault once set using zowe config secure --gc

### ISSUE THREAD

**Issue by davidkjackson54** [zowe/zowe-cli#1682]
For this example>
2 profiles A and B  - each have userid and password set to secureArgs
and a default profile also with userid and password set to secureArgs

I issue zowe config secure --gc and set: 
the userid X for profile A and set userid Y for profile B
and I set userid Z for the default profile

THer are now 3 sets of values stored in the WIndows Credential store. 
All works fine and the user can issue commands against profile A (which uses userid X) and against profile B (using userid of Y) 

Now , the user wishes to remove the credentials entirely for profiles A and B and now use the default userid of Z that is saved in the default base profile. 
When I issue `zowe config secure --gc`
The prompt states:
```
PS D:\source\> zowe config secure --gc
Enter profiles.A.properties.user - blank to skip:
Enter profiles.B.properties.password - blank to skip:
```

Simply pressing <enter> leaves the existing values alone.  The comment of 'blank to skip' does seem misleading.
If I try entering a space  - that is the value that the userid is saved as.
Likewise, I have tried entering '' and also "" but that also is stored as the value in the credentials store.  

There doesn't seem to be any value that can be entered to actually subsequently remove the value from the credential store.

Not having the means to subsequently remove a userid/password pair seems to be a bug rather than a feature request.

The only way I can find of doing this is to delete the zowe entry entirely from the operating system credential store but I think that is risky to tell a regular user to go do that.

**Comment by t1m0thyj** [comment]
When property names are defined in the "secure" array for a profile like in the example below, that links it to a secure value saved in the vault.
```
    "profiles": {
        "my_zosmf": {
            "type": "zosmf",
            "properties": {
                "host": "example.com"
            },
            "secure": ["user", "password"]
        }
    }
```

To remove them from the vault, users can edit the zowe.config.json file to either remove the secure array or comment it out (by adding `//` in front of the line). The next time they run `zowe config secure` those secure values should be removed from the vault.

In the case that a user has deleted a `zowe.config.json` file and wishes to remove its secure properties from the vault, they can run pass the `--prune` flag to `zowe config secure` since Zowe CLI 7.13.0.

**Comment by davidkjackson54** [comment]
In this scenario , the user doesn't want to modify the Teams profile (nor should he have to as it was supplied to him).  
His Teams profile gives the user the option to enter his credentials at each individual profile level and also specify a default value in his default base profile.  
He first opts to enter his credentials for each of his profiles but later decides that in fact he wants to use the common userid defined in his Default base profile.  He can't undo what he did when he set his credentials against each individual profile.

IT seems a shortcoming that `zowe config secure --gc` is missing the ability to remove a secureArgs once set.

**Comment by gejohnston** [comment]
The purpose of a user configuration file (zowe.config.user.json) is to enable a user to alter their configuration without changing a shared team configuration file. Controlling such config changes through the zowe.config.user.json file would be consistent with our original design scheme.

The current implementation of the zowe.config.user.json file combines the team config and user config in an additive fashion. Perhaps the best way to address this problem would be to implement some means for the user config file to **REMOVE** some properties that might be present in the team config file.

**Comment by davidkjackson54** [comment]
I disagree. 
We are not changing the configuration nor do we want to remove any properties as defined in the profile. 
We are simply making use of the configuration as it is provided. 
By providing secure args at the service profile level and also at the default profile level (both of which are fully supported in the profile definition).  - allows the user to either logon using service profile credentials (which take precedence over the base profile default) or the base profile credentials. What the user cannot do is to switch from one usage to the other once credentials have been established as there is no mechanism to remove credentials from the secure credential store using `zowe config secure --gc`.  
That seems a big omission. Leving the user no option but to have to actually go and delete the zowe entry from the credential store., 

It isn't a profile issue - it is the lack of being able to change what is stored in the credential store once established.  All it needed was the zowe config secure --gc to have the means to enter a value that then causes the underlying entry to be removed from the credential store.  
You allow a <enter> key to be pressed to skip the value but no option to remove an existing option.

**Comment by gejohnston** [comment]
By design, the existence of a property (including a secure user or password) in a service profile means that the property in the service profile is supposed to be used instead of the base profile. It seems like more of side-effect that the absence of service profile creds in the secure vault results in the values being used from the base profile.

None-the-less, this is an existing side-effect, and we cannot blame people for taking advantage of an existing behavior. One possible way to accommodate this functionality would be to add another option to the “zowe config secure” command, something like “--delete-on-enter”.

The prompt text in the “zowe config secure” command could be something like the following, depending on whether or not the “--delete-on-enter” option is specified:

    Enter profiles.A.properties.user – Press ENTER to retain:
or

    Enter profiles.A.properties.user – Press ENTER to delete:

A Zowe team review will determine the correct approach and details of operation.

**Comment by gejohnston** [comment]
Another variation could be to allow 2 special character sequences during the prompt, and require no command-line option. This would allow the choice to be made for each property, as it is being prompted for. The more elaborate description could be displayed once at the beginning, instead of during each prompt.

    zowe config secure
    At any prompt, press ENTER to retain the previous value, or
    press CONTROL-D  ENTER to delete the previous value.
    
    Enter profiles.A.properties.user: 
    Enter profiles.B.properties.password:

**Comment by gejohnston** [comment]
There is an additional consideration on the use of CONTROL-D (which I thought would help people remember that it stands for DELETE). CONTROL-D on Linux systems is the End-of-file indicator. It might terminate the user input stream. We may need to select a different meta-character.

To make this easily usable in Zowe Explorer the functionality must be implemented in the client-side API of Zowe CLI (much of which might already exist for the “zowe config secure” command).

Some of these details are irrelevant to the end user. I just want the various considerations on the record for such time as the engineering team undertakes any work on this issue.

**Comment by davidkjackson54** [comment]
Yes agreed on the affect CTRL-D would have on Linux.  Maybe as we are asking the user to remove a previously set credential - that he has to enter 'DELETE' in uppercase as a keyword.

**Comment by davidkjackson54** [comment]
@gejohnston - I have had 3 customers contact me over the past month regarding this issue. One has many dozens of subsystems and is using the Teams profile and the features that it provides but is having a lot of problems arising from this inability to remove credentials once that have been established for a given profile i.e. he wishes to revert to using the values set in the default profile for a period of time.  The customer is unhappy at being told that the only option currently is to delete the zowe entry from the Windows Credential store as he then has to establish upwards of 20- 30 secure value pairs again. 

I don't know if this defect is on the radar for being addressed any time soon.

**Comment by davidkjackson54** [comment]
@gejohnston  @JTonda  @adam-wolfe 
Seems like you have now moved it from an obvious bug to now being an enhancement as a means to simply not fix the problem.  Gene himself agreed that it exposes an issue in the existing functionlity provided.
Regular uses are not developers and are not going to come on to github and 'upvote' this. Instead they come to me and raise their concerns as noted above. 
This is a clear and obvious bug for a feature that you provide in zowe 2 profiles that only  provides half of what the functionality requires,   Not only does this impact VSCode Explorer extensions but it also fails within zowe cli itself.

**Comment by gejohnston** [comment]
@davidkjackson54 - We plan to resolve this issue by allowing the user to delete a value from the OS secure vault. During the interactive prompting of the 'Zowe config secure' command the user will be able to specify a special value (to be determined) that will delete the secure value from the OS vault. It will NOT delete the property name from the secure array in the zowe.config.json file. The existing prompting options of adding a value that does not currently exist, replaing a value that does exist, or leaving the current value in place will continue to be available.

We labeled this issue as 'priority-high'. The Zowe community's definition of 'priority-high' is:

   "An important issue that should be at least considered for the next PI, ideally within this one, if there is spare capacity."

It is our intention to adhere to that guideline.

The plan above will be implemented in Zowe CLI. A separate issue should be created in the Zowe Explorer GitHub repository for requested changes to Zowe Explorer.

**Comment by davidkjackson54** [comment]
Gene
This affects the general Explorer community and not just limited the zowe Explorer.  
You create this addtional function to help the VSCode Explorer developers simply profile access.
https://medium.com/zowe/an-api-to-simplify-retrieval-of-zowe-profile-information-a1293656de21 

Presumably there would be some change to ProfInfo to address this? Just as we use ProfInfo.updateProperty currently,

**Comment by gejohnston** [comment]
Hi David,

It is legitimate to have a secure array within a base profile and within individual service profiles. However, once a secure value is stored in the vault for an individual service profile then that service-value will always override the corresponding property from the base profile.

Zowe CLI does not currently expose the ability for an end user to directly delete values from the vault. Our thinking was that users who no longer wanted to use credential values from the service profile would delete those property names from the secure array in the service profile. Then the base profile property values would be used again.

As I recall from your previous issue, you deployed a team config to all users with user & password in the secure arrays within the base profile and in every service profile. This allowed your users to set credentials in some service profiles but not other service profiles. However, once a user sets credentials in a service profile, they were locked into that choice. Because you legitimately do not want users editing the shared team config, the user cannot delete the user and password property from a given service profile.

Here are my thoughts on another way of trying to achieve the objective using existing Zowe capabilities. I would only place user and password into the secure array of the base profile in the shared team configuration. No service profiles would have credentials in the shared team configuration. For a user who needs different credentials for a specific service, I would have that user create a zowe.config.user.json file. That user config file would only have to contain the desired service profile, and that service profile would only have to contain a secure array with user and password. The result will be that everything about that profile will be used from the team config, except that the user and password will be overridden for that service. If the user wants to revert back to the common credentials from the base profile, the user would delete (or comment out) the user and password from the secure array in the user config file.

Granted, end users will have to edit a config file, but it would not be the team config file shared by all other users. It would be their personal configuration file. It was part of our intention that users edit configuration files to control their desired options. You could help the users by distributing a skeleton zowe.config.user.json file that has all of the available profiles with no values and empty secure arrays. Thus, nothing would be overridden until a user decides to make an update to their own zowe.config.user.json file.

You may have other constraints that may make my suggested approach undesirable. I just wanted to give you an approach that does not require you to wait for future enhancements.

To programmatically delete a value from the secure vault, I believe that a recent update to our API (https://github.com/zowe/imperative/issues/917) enables you to set the value of a secure property to undefined, which will delete that value from the vault. We did not have time to re-test that capability in our lab before sending this response, but it may also be an experiment that you could easily try yourself.

**Comment by davidkjackson54** [comment]
@gejohnston 
Thanks for the detailed update it helps and I willl pursue the option of a user config for such overrides and see if that is considered acceptable.

**Comment by gejohnston** [comment]
@davidkjackson54 - One final note - When using user config files as described above, make sure to keep the user config file in the same directory as the team config file (either the user's global directory or in a project directory). Mering a user config file in a project directory with a shared team config file from the global directory will not give the results that you want.
