### ISSUE TITLE
Cargo required in some cases for Secrets for Zowe SDK on Linux

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli#1787]
**Describe the bug**

Maybe not a bug, but something that should be noted in user documentation. Somewhat related to https://github.com/zowe/zowe-cli/issues/1774. I have not tested this extensively, just with an installation of Ubuntu 18.4.6.

Users may need to have cargo installed in order to use secure credential storage on Linux.

Trying to store credentials when Zowe CLI is installed without cargo installed (secrets sdk missing):
![image](https://github.com/zowe/zowe-cli/assets/122040687/bd4dd25f-1210-43d4-bf75-d355573c8f92)

Trying to store credentials when Zowe CLI is installed with cargo installed (secrets sdk ok):
![image](https://github.com/zowe/zowe-cli/assets/122040687/cdf730ba-99f8-4dad-a697-c6ad1cd5b5ac)

Secrets for Zowe SDK installation when Cargo is not installed:
![image](https://github.com/zowe/zowe-cli/assets/122040687/77884ec8-abed-4cfe-ab3b-12a22500c2cf)

**Expected and actual results**

**Describe your environment**

Ubuntu 18.4.6 (no gui)

**Additional context**

**Comment by traeok** [comment]
Cargo is still a prerequisite for users who do not have a supported platform or architecture for the Secrets SDK. But, I pushed up #1788 for review - this PR will adjust the install failure so that it silently fails if the error is unrelated to a missing module. This keeps the behavior consistent w/ the previous behavior from node-keytar.
