### ISSUE TITLE
Max poll attempts reached

### ISSUE THREAD

**Issue by tucker01** [zowe/zowe-cli#188]
I attempted the following command:

```
$ zowe jobs sub lf xxxxx --directory output --zosmf-p xxxxx
Command Error:
Error obtaining status for jobname "xxxxxx" jobid "JOB61840".
Error Details: Reached max poll attempts of "100"
```

There is no option to influence the number of polling attempts (or make it infinite).

**Comment by Colin-Stone** [comment]
Has something here changed recently, any work arounds?.

**Comment by tjohnsonBCM** [comment]
The default timeout of 5 minutes was removed in both [`master`](https://github.com/zowe/zowe-cli/pull/654) (@zowe/cli >= 6.7.1) and [`lts-incremental`](https://github.com/zowe/zowe-cli/pull/657) (@brightside/core >= 2.36.3), so now job status is checked indefinitely.

The new behavior should give users more flexibility to choose the timeout of the command, since previously it was hard-coded, but now it is possible to enforce any desired timeout within a script that calls the Zowe CLI command.

**Comment by Colin-Stone** [comment]
Thanks Timothy sounds much neater. Is there a sample script or recommended pattern available which shows how a customer can implement the timout feature?

**Comment by tjohnsonBCM** [comment]
I don't think we have a sample script for it currently. There is a [timeout](http://man7.org/linux/man-pages/man1/timeout.1.html) command in Bash that looks like it could be an easy way to implement it.
