### ISSUE TITLE
zowe cli V2 help contains deprecated commands which are not relevant

### ISSUE THREAD

**Issue by cumarav** [zowe/zowe-cli#2137]
during zowe profile creation in  the cli V2 I did not find descriptive help for the profile management.
Command `zowe config  profiles --help-web` opens  common list of command for v1 and v2. It is very is confusing because too lot of command are irrelevant, will be good to have an option to see only what can be used. Profile management in v2 is not described well.

**Comment by gejohnston** [comment]
I am a little confused about this issue. The title and the description of this issue focus on different topics.

Regarding “help contains deprecated” commands: All V1 ‘zowe profiles …’ commands are deprecated in V2. That is why the help displays comments about them being deprecated. The ‘zowe profiles’ commands do still work in V2, but will be removed in V3.

The recommended practice in V2 is to create and use a new style of configuration contained in a file named zowe.config.json. The actions to create and manage such a configuration is documented in the Zowe doc site. The following doc topic provides an introduction to creating your Zowe client configuration:

[Initializing team configuration](https://docs.zowe.org/stable/user-guide/cli-using-initializing-team-configuration)

The command that you list in your description just lists the set of profiles that you have created within your zowe.config.json file. That is what the help describes for the ‘zowe config profiles’ command.

![image](https://github.com/zowe/zowe-cli/assets/37119146/c4d5ee61-3cab-4dad-b7e2-7f713a3d08c1)


If you have created no configuration, the ‘zowe config profiles’ command lists nothing, because you have no profiles yet.

Your best course of action is to follow the instructions at the Zowe doc site mentioned above.

**Comment by cumarav** [comment]
I need to set up multiple profiles for multiple mainframes, earlier it was possible to achieve  - now 
```
An error occurred trying to create a profile.
Profile IO Error: A Zowe V1 profile operation was attempted with a Zowe V2 configuration in use.
```
and in web help I see __3 words__ : *Displays profile paths.*
Command itself actually __does not show paths__ .
Plus I see deprecated commands which does not work
Still no idea how to add second environment.

**Comment by gejohnston** [comment]
In your most recent comment you did not show what command you actually entered. So, I must guess what it was.

This error occurs when you already have a new-style configuration (zowe.config.json) and you issue a command to update an old-style profile. My guess is that you must have issued a command like 'zowe profiles create ...'.

Zowe CLI will not run an old 'zowe profiles' command when you already have a zowe.config.json file in place. I do not know how you created a zowe.config.json file, but it appears that you definitely have one. The following command will show you where your zowe.config.json file resides.

```
zowe config list profiles --locations --root
C:\some\directory\path\zowe.config.json
```

You have 2 options.

1. Edit your zowe.config.json file to add your new profiles. This is the recommended approach.

2. Delete your zowe.config.json file and use the old 'zowe profiles' commands to add your new profiles into the old-style profiles location. This is not a recommended approach. As you noticed, the 'zowe profiles' commands are deprecated in Zowe V2, although they do still work. Those 'zowe profiles' commands are gone in Zowe V3.

Again, I suggest that you read the Zowe doc site for information on how to construct profiles in your zowe.config.json file.

**Comment by adam-wolfe** [comment]
Thank you for your feedback, however no further action is planned with respect to this issue.

In Zowe CLI V2:
- `zowe profiles` commands apply only to V1 profiles
- `zowe config` commands apply only to team configuration files (first introduced in Zowe V2)
  - One exception is the `zowe config convert` command which converts V1 profiles to a team config

In V2, both command groups are relevant. In V3, only the `zowe config` command group will be available.
