### ISSUE TITLE
Console logging during tests

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#29]
_From @tucker01 on September 17, 2018 15:11_

We should remove all logging to stdout during jest test execution (interferes with jest console messages). 

_Copied from original issue: gizafoundation/brightside#247_

**Comment by JTonda** [comment]
_From @AHumanFromCA on September 20, 2018 20:50_

Can I propose a slight change to this requirement? How about we have an environment variable that a global test hook checks to determine if log messages should be output?

I know sometimes it is helpful to see the log messages but maybe we can turn it off when not needed?

For example:

When writing unit tests in intellij it can track which messages came from which test so I can follow any code trace messages really easy when debugging / developing new tests. Turning off the ability to see these prevents me from possibly seeing some useful information to help solve a problem.

**Comment by JTonda** [comment]
_From @tucker01 on September 21, 2018 12:54_

Yeah we could introduce a debug mode for tests 🚑 

I think we talked about this IRL, but there was a test logger... not sure if we use that anymore.

**Comment by JTonda** [comment]
_From @ChrisBoehmCA on September 21, 2018 12:57_

The logs could potentially go to the __tests__/__results___/data/<workingdir> instead of stdout so that you could still read them but they wouldn't mess up the Jest output animation

**Comment by JTonda** [comment]
_From @AHumanFromCA on September 21, 2018 14:9_

@ChrisBoehmCA That's fine but I would like to have the option for them to still go straight to stdout. Mainly because when running in intellij I can click on a specific test and it knows which messages were logged during that test and only outputs those. It can even show every log message for a describe.

And realistically the only problem we see is that the output during test execution is garbled. No functional items are broken by having log messages intertwined...You still see proper code coverage reporting, final failure reports, and exit statuses.

**Comment by MikeBauerCA** [comment]
@zFernand0 can we close this issue?

**Comment by zFernand0** [comment]
I'm afraid that not all tests have being properly cleaned up, and unless I'm missing it, I couldn't find this feature.
`have an environment variable that a global test hook checks to determine if log messages should be output`

I don't know how much effort we may want to put into this since...
`the only problem we see is that the output during test execution is garbled. No functional items are broken by having log messages intertwined...You still see proper code coverage reporting, final failure reports, and exit statuses.`

It'd certainly be nice to have clean output (see image below). But again, it's just a nice to have.
![image](https://user-images.githubusercontent.com/37381190/109877099-9ab16400-7c40-11eb-87d1-ae45b7a367ed.png)

Unless someone strongly disagrees, I vote for closing this issue.
If someone volunteers in the future, we'll definitely welcome the contribution! 😋

**Comment by MikeBauerCA** [comment]
Will close and reopen if needed. Thanks!
