### ISSUE TITLE
Got zosmf error when uploading JCL file to dataset

### ISSUE THREAD

**Issue by LiangXuehongBJ** [zowe/zowe-cli#483]
When I upload jcl file to dataset, I got error as following:
Could you please help find the reason?

Thank you!

[stud22@lxrh4 iFrame]$  zowe files upload file-to-data-set sample.jcl "stud22.jcl(sample)"
success: false
from:    /home/stud22/ZoweHandsOnLab/iFrame/sample.jcl
to:      STUD22.JCL(SAMPLE)
error:
  message:
          z/OSMF REST API Error:
      Rest API failure with HTTP(S) status 500
      category: 6
      rc:       8
      reason:   520
      message:  fwrite() error
      details:
        - EDC5003I Truncation of a record occurred during an I/O operation. (errno2=0xC0440016)
        - __amrc: __last_op=151 __code=0x00000000

  stack:
    - Error: z/OSMF REST API Error:
    - Rest API failure with HTTP(S) status 500
    - category: 6
    - rc:       8
    - reason:   520
    - message:  fwrite() error
    - details:
    -   - EDC5003I Truncation of a record occurred during an I/O operation. (errno2=0xC0440016)
    -   - __amrc: __last_op=151 __code=0x00000000
    -
    -
    -     at ZosmfRestClient.populateError (/node-v8.16.0-linux-s390x/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/rest/src/client/AbstractRestClient.js:463:16)
    -     at ZosmfRestClient.onEnd (/node-v8.16.0-linux-s390x/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/rest/src/client/AbstractRestClient.js:383:31)
    -     at IncomingMessage.res.on (/node-v8.16.0-linux-s390x/lib/node_modules/@brightside/core/node_modules/@brightside/imperative/lib/rest/src/client/AbstractRestClient.js:318:18)
    -     at emitNone (events.js:111:20)
    -     at IncomingMessage.emit (events.js:208:7)
    -     at endReadableNT (_stream_readable.js:1064:12)
    -     at _combinedTickCallback (internal/process/next_tick.js:139:11)
    -     at process._tickCallback (internal/process/next_tick.js:181:9)

file_to_upload: 1
success:        0
error:          1
skipped:        0

z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
category: 6
rc:       8
reason:   520
message:  fwrite() error
details:
  - EDC5003I Truncation of a record occurred during an I/O operation. (errno2=0xC0440016)
  - __amrc: __last_op=151 __code=0x00000000

**Comment by tucker01** [comment]
Normally this occurs when you have a line in your file that is longer than the LRECL of the data set you are uploading too. Sometimes this can be a bit tricky, because the line might contain whitespace. Normally, if you highlight the lines in your editor, you can see which one might be causing the problem.

**Comment by MarkAckert** [comment]
This appears to be working as expected since z/OSMF returns a reasonable enough error message in the situation - `EDC5003I Truncation of a record occurred during an I/O operation. (errno2=0xC0440016)`. This issue can serve as additional context and documentation for anyone else running into it. If in the future someone feels we should be performing additional pre-flight validation checks before submitting requests to z/OSMF, please create a new issue.
