### ISSUE TITLE
Log messages output to stdout when using APIs outside of zowe-cli

### ISSUE THREAD

**Issue by tucker01** [zowe/zowe-cli#511]
If the imperative logger is not initialized and the APIs (such as those in `GetJobs.ts`) are invoked, log messages are output to stdout. This should not be the default.

**Comment by dkelosky** [comment]
Agree it's not a good default.  You can init imperative to get around this, or for less overhead:

```typescript
import { Session, ISession, Logger, LoggingConfigurer } from "@zowe/imperative";
...
Logger.initLogger(LoggingConfigurer.configureLogger(".something", { name: "something"}));
```

You should be able to init with logging turned off, via:
```typescript
Logger.initLogger(LoggingConfigurer.configureLogger(".kelosky", { name: "kelosky", logging: { appLogging: {level: "off"}}}));
```

This is pending a fix to imperative: https://github.com/zowe/imperative/issues/301

**Comment by sosadchuk** [comment]
Any updates on this?

The problem is not only in missing Logger init, but with indirect dependencies as well. For example, we are able to suppress some messages by providing a mock with jest:
```
import { Logger } from "@zowe/imperative";

jest.spyOn(Logger, "getLoggerCategory").mockReturnValue(getMockSilentLogger());
Object.defineProperty(MonitorJobs, "log", { value: getMockSilentLogger() });
```

But we struggle with mocking an indirect dependency when calling `GetJobs.getJobsByOwnerAndPrefix()`

Would be great if imperative.Logger would honor the environment variable `ZOWE_IMPERATIVE_LOG_LEVEL`, and set a given log level for direct / indirect imperative dependencies.
