### ISSUE TITLE
Expand help text of --data-set-type on create data set commands

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#52]
_From @dogboydog on June 29, 2018 14:44_

We should explain the possible values and purpose of the data set type option are on zos-files create commands so that new users can determine what to specify 

_Copied from original issue: gizafoundation/brightside#143_

**Comment by JTonda** [comment]
_From @PeteSwauger on August 29, 2018 16:17_

This is related to ZosFiles should allow additional values for the DSnType option which wants more dsnType's supported.  Currently only 'LIBRARY' is supported which allows the creation of a PDSE.

**Comment by MikeBauerCA** [comment]
Bump on this one as someone asked about the possibility of creating a PDSE via the Zowe CLI today 👍 ... maybe an example in the help would be nice letting users know that the creation of a PDSE is possible. z/OSMF provides an example of PDSE creation via the API in their doc: https://www.ibm.com/support/knowledgecenter/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua700/IZUHPINFO_API_CreateDataSet.htm

**Comment by t1m0thyj** [comment]
Discussed with @zFernand0 the idea of defining `allowableValues` for the "--data-set-type" option, similar to this:
https://github.com/zowe/zowe-cli/blob/57e30025034a001bcba1eaad1650a0f8828def9c/packages/cli/src/provisioning/list/instanceInfo/InstanceInfo.definition.ts#L43-L46

In this case the allowable values would be the ones mentioned [here](https://github.com/zowe/zowe-cli/pull/1043#issuecomment-872492530):
> Dataset type: BASIC,EXTPREF,EXTREQ,HFS,LARGE,PDS,LIBRARY,PIPE

We decided to document these values in the command description, rather than using `allowableValues`, and wanted to document why for future reference 🙂 
* ✔️ For some commands like "files mount fs --mode", using `allowableValues` makes sense
  * [z/OSMF documentation for the endpoint](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-mount-zos-unix-file-system) clearly specifies these as the only allowable values.
  * There are only 2 options allowed ("rdonly" and "rdwr") and it seems unlikely for this to change in the future.
* ❌ For other commands like "files create ds --data-set-type", using `allowableValues` seems undesirable
  * [z/OSMF documentation for the endpoint](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-create-sequential-partitioned-data-set) doesn't document the allowable values, although they are listed elsewhere.
  * There are many options allowed (8 of them) and it seems plausible for a 9th to be added in the future. If this happens, enforcing a set of `allowableValues` in Zowe CLI would make us less future-proof.
