### ISSUE TITLE
Prompt for user name and password when submitting a command from a profile that is missing those.

### ISSUE THREAD

**Issue by jelaplan** [zowe/zowe-cli#587]
The Zowe Explorer VS Code extension has introduced optional user name and password into profiles.  For Zowe CLI, those profiles will be available for use with commands. But, if a user submits a command with a password-less profile, they will need to enter a password as a option on the command line or edit the profile ahead of time. 

I would like the system to prompt for those if they are missing. See related story 
https://github.com/zowe/zowe-cli/issues/538

![image](https://user-images.githubusercontent.com/3207260/68898496-8ff65700-06fd-11ea-8414-8927baba4694.png)

**Comment by MikeBauerCA** [comment]
As mentioned in https://github.com/zowe/vscode-extension-for-zowe/issues/373#issuecomment-562696447, I believe the Zowe CLI should be enhanced so that all profile fields are optional and when running a command if an option is not supplied and there is no default option, the user is prompted.

Profiles themselves are optional, so I do not see why they would have a required field.

**Comment by tjohnsonBCM** [comment]
Zowe CLI now prompts for user and password if they are missing on a command:
![image](https://user-images.githubusercontent.com/50887074/91617686-879e9e00-e956-11ea-8dbe-2061d1c12389.png)
