### ISSUE TITLE
Update @zowe/imperative dependency

### ISSUE THREAD

**Issue by mr-eshua** [zowe/zowe-cli#628]
Hello.

Zowe CLI requires an exact version of `"@zowe/imperative": "4.4.4"` at the code level of v6.5.0. It is a proposal to update dependency to "4.4.5", since it has a `yargs`-related vulnerability issue fixed lately OR, probably, if it is appropriate - to specify that dependency as "~4.4.5" to make sure Zowe CLI will have all the minor bugfixes and security covered if imperative API will be updated in the further.

Thanks in advance!

**Comment by tjohnsonBCM** [comment]
Thanks for reporting this, the Imperative version was changed in #630 to require "4.4.6".

Leaving it as an exact version in `package.json` is OK, since @zowe-robot updates the Imperative version to the latest patch automatically. This automatic versioning is temporarily down due to some infrastructure changes in the Zowe CLI build system, but should be back again soon.

**Comment by mr-eshua** [comment]
Thanks a lot for fixing it! And for clarification on the build system. That is good to know.
