### ISSUE TITLE
servlet key question

### ISSUE THREAD

**Issue by markons** [zowe/zowe-cli#642]
I get the error message "No servlet key was supplied" at calling a TSO command. How can I solve it pls.? I could not find the corresponding reference in the manuals.

**Comment by Alexandru-Dumitru** [comment]
Hi @markons. Are you using `zowe tso send` ? Because this command would require you to open an address space first with `zowe tso start address-space`. Then you receive a servlet key which you use as a parameter to `zowe tso send`. Alternatively you can use `zowe tso issue`, which does all these things for you in the background (open address-space, issue command, then close address-space).
Here is the online help for easy reference https://docs.zowe.org/stable/web_help/index.html?p=zowe_zos-tso

If you have issues with `zowe tso issue`, please provide a snippet of the error and details of `zowe --version` you are using.

**Comment by markons** [comment]
Hi Alex,

thanks first. As far as I can see, I miss the appropriate access right to start a new(?) TSO address space.

![image](https://user-images.githubusercontent.com/2115566/72784980-62acb480-3c2a-11ea-9e8f-8a6a891a3f04.png)

**Comment by Alexandru-Dumitru** [comment]
At least this is a step in the right direction 😄. Could you please sort this our with your system administrator and then try again? Thanks.

**Comment by markons** [comment]
Hi Alex,

I've got the access in the meanwhile, Zowe functions now well. Thanks for your support!

Gábor
