### ISSUE TITLE
Spike - research ability to store all profile options in a single base profile

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#749]
With the recent SSO enablement feature in the Zowe CLI, the concept of a base profile was introduced. This is convenient for storing connection type info (host, username, password) in a single location rather than in multiple service profiles. It would be nice if we could manage all profile type information in this single profile. Research is needed to determine how to best accomplish this. 

Currently, every profile has a schema that stores info about its properties (e.g. zosmf_meta). We need to enhance base_meta to be dynamic so that as plug-ins are installed, its definition can change to accommodate additional properties.

We also need to determine how users can config these options in base profiles via CLI commands. Could we use a naming schema to accomplish this? E.G. zowe profiles create base default --cics-region-name <Region_Name> where cics is the alias for the existing cics profile available after the cics-for-zowe-cli plug-in is installed. 

Should we provide instructions on how to update the yaml file directly? Should base profiles be created with all properties (if not specified on command line, leave empty) to allow for easy editing? Should users be able to import/export profiles?

**Comment by dkelosky** [comment]
long term, if might be nice to allow for a single profile in a given project without needing a `.meta` alongside it, so that users could source control and share a single `.zowe/base-profile.ts` that would contain all configuration needed to run commands.

**Comment by dkelosky** [comment]
FYI, here is an example showing a potentially reworked `base-profile` which could contain `zosmf` (and other profiles) within it:
![image](https://user-images.githubusercontent.com/14940561/90548027-5a820c80-e15a-11ea-9d4a-ef40a08bdcfc.png)

We might consider something like [json schema](https://json-schema.org/) instead of our `meta` file.  This would allow for IntelliSense when editing these profiles directly in VS CODE.  In the example above, `port` is identified as wrong since it's not an integer type according to the schema.

Users could also get hints, and default values using json schema:
![jsonexamples](https://user-images.githubusercontent.com/14940561/90548763-71752e80-e15b-11ea-90ad-950688f95cf3.gif)

After allowing for a single profile and an alternate schema, a final step might be to allow for a project-based profile - meaning, if there is a consolidated `base-profile` in the current working directory, it would take priority use in Zowe CLI.

CC @zFernand0

**Comment by MikeBauerCA** [comment]
@dkelosky thank you for the detailed examples. If pictures are worth 1,000 words then how many words are GIFs worth? :)

What do you think about supporting both `.yaml` and `.json` formats?

**Comment by dkelosky** [comment]
😀

I’m a little indifferent; we have both in Zowe CLI. JSON5 allows comments. VS Code JSON schema is better for JSON than YAML; perhaps the latter will be made better. 

To recap the high level proposal:
- allow for a single base profile to contain all config
- remove meta file requirement and maybe use JSON schema instead
- allow for a profile to be used if it’s in the current directory

For fire last item, we’d have to work out credential management and where plugins are installed (so both are not checked into source control if used that way)

**Comment by MikeBauerCA** [comment]
Would "remove meta file requirement and maybe use JSON schema instead" be for all profiles (base + service)? Do you envision this being a breaking change for users with existing profiles? If so, we should offer a migration utility. If so, do we want to continue having the option for multiple configuration files, or simply transition current users to this new single configuration file?

**Comment by dkelosky** [comment]
Hopefully we'll be backward compatible.  Meaning, if a `meta` file is present, we'd continue to use it.  Otherwise, we'd reference the schema via `$schema` tag.  Longer term though, we might consider to migrate entirely away of `meta` pending user feedback. 

This would allow for a more dynamic schema.

**Comment by MikeBauerCA** [comment]
I'm also thinking about how Zowe Explorer handles profile creation etc. and the fact that multiple services are integrating with it. If the go forward path was JSON schema, perhaps Zowe Explorer could provide a GUI approach (quick pick dialogs) for direct to z/OSMF setup as it does today for folks getting started, but for advanced setup, just open the JSON file. We will of course need sufficient documentation on how to setup this config for various environments. One concern is that our personas may not be familiar with editing JSON config today but if they using these technologies in DevOps, it seems par for the course.

**Comment by dkelosky** [comment]
@zFernand0 reminded me that perhaps we'll look specifically at [JSON schema 7]("$schema": "https://aka.ms/terminal-profiles-schema") to help users manually edit profiles.  

Windows Terminal and GitHub Actions appear to use this standard.  The schema's can be hosted on stores like https://www.schemastore.org/json/

**Comment by phaumer** [comment]
> I'm also thinking about how Zowe Explorer handles profile creation etc. and the fact that multiple services are integrating with it. If the go forward path was JSON schema, perhaps Zowe Explorer could provide a GUI approach (quick pick dialogs) for direct to z/OSMF setup as it does today for folks getting started, but for advanced setup, just open the JSON file. We will of course need sufficient documentation on how to setup this config for various environments. One concern is that our personas may not be familiar with editing JSON config today but if they are using these technologies in DevOps, it seems par for the course.

Changes to the meta file format can completely break other consumers as they did with Zowe Explorer. Zowe Explorer uses the meta file to generate the prompts for creating profiles. The thinking was that any Zowe Explorer extender can therefore easily add more properties for their plugins that Zowe Explorer would ask about.  By using profiles now to not only store user information, but to also use it for runtime information such as tokens completely Zowe Explorer now in that use case.  More governance for such changes and analysis of the impact it has for other squads would be a good thing to have.

**Comment by MikeBauerCA** [comment]
One benefit of having the token in the base-profile is that it can be easily accessed and shared by all clients. This provides a means to have SSO for all clients (Zowe CLI, Zowe Explorer and their plug-ins/extensions) interacting with services that participate in SSO via the Zowe API Mediation Layer.

Regarding the single profile option, we may start with a single profile that is part of a project that can be checked into source control. Today, profiles are all user based and are typically stored in the user's home directory. We will plan to allow for a specially named file (let's call it zowe.json for now) to be checked into source control. When running commands in a directory that contains a zowe.json file, the zowe.json file will be to sole source of config info and user profile settings will be ignored. Zowe Explorer could consider respecting the file if it is in their workspace. Then getting started would be as easy as cloning a GitHub project and logging into the API Mediation Layer. Without API Mediation Layer participating SSO services, they may be asked for creds multiple times or choose to store them if they are not changing very often.

**Comment by phaumer** [comment]
The tokens can still be easily accessed if they would be placed in a different file using a separate meta schema. If we want to create editors for profiles then we need to separate machine generated runtime information such as tokens from data the users needs to enter. At least this needs to be differentiated in the schema so that the editor knows which of the properties are for user editors vs are used by the machine. Right now Zowe Explorer keeps asking me for token type and values when creating a profile, which does not make sense to users.

This should be like a cookie store in a browser.  If it is a separate name-value store it could be stored under the profile type/name just like how cookies are stored in the browser for a url.

**Comment by dkelosky** [comment]
Your points are understood.  For background, our goal was to emulate `.npmrc` behavior.  If you `npm login` to publish npm packages, your token is stored within `.npmrc`.  Likewise, you can edit `.npmrc` directly or indirectly through `npm config` commands.  Longer term, we're wonder if that's a better experience for Zowe Explorer users.  

Perhaps Zowe Explore should not prompt for all fields contained within the `meta` definition.  In that way, with good intellisense (via something like JSON schema), it might be easier / more intuitive to edit profiles directly or through the CLI.  What are your thoughts?

**Comment by phaumer** [comment]
For npmrc you typically enter the token as a user, i.e. artifactory gives you the entire object to copy and then you newer change it again. That kind of information I would also put into the profile file.  However, tokens that I would get with zowe auth are meant to be temporary and expire after a few hours. Those I get created every time when I start a session, but not when I create my profile.

As a quick workaround for the current "breakage" I would suggest to add at least a property such as `"hidden": true` to the meta schema, so that Zowe Explorer can decide, which items to show and which not.

**Comment by dkelosky** [comment]
Thanks @phaumer.  The `.npmrc` auth token is something that expires or can be invalided - it must be changed at some point.  Perhaps we're talking about different things.  

In any case, I see patterns for both combining (e.g. `.npmrc`) and separating (e.g. AWS credentials profile) types of data.  So, in the upcoming PI we'll look at:

- something like a `hidden: true` in the schema for VS Code prompting purposes
- separating user tokens to another location
- migration of old schema to a standard 

For the last topic, we're still thinking of some modification to our current schema approach, whether it is JSON 7 or something else.  None of the tooling referenced in this issue uses an adjacent, external meta/schema file as we have today for Zowe CLI.  

Last note, tokens may also come from command line input or environmental variables for Zowe CLI (likewise for `firebase`, `aws`, and lots of other tooling).  They don't need to be stored in a profile and Zowe CLI allows for this today.

**Comment by tucker01** [comment]
This issue seems to cover a range of suggestions, so I'm going to add to the "configuration" discussion here (instead of opening a new thread). 

As a side note, if you're not already aware... You can store any and all options in any profile. Imperative merges the contents of ENV vars, profiles, and CLI options to provide the complete set of arguments. For example, you can place `prefix` in a `zosmf` or `base` profile and it will be honored by the CLI (if the command has a `--prefix` option). 

I'm currently taking a stab at creating a consolidated/simplified JSON configuration for Imperative based CLIs. There's a sizable amount of considerations and I believe a working example would help us evaluate the details and user experience.

**Comment by phaumer** [comment]
I reviewed the schema a little bit and want to propose a slightly different way of structuring the schema to make editing it in a yaml/json editor more intuitive.

Instead of doing an array of objects that have to be named by the user, did you consider designing the schema more like a form to make it easer for the user to enter it and to better provide code completion? With the current schema there is no code completion until the user realized that they have to create an array and a named object themselves. If you organize it more like the example below the entire process of entering a file could be driven by code completion. It is also consistent with the way you see yaml being used by many cloud frameworks such as devfiles and plugin files in Che:

```yaml
name: Johns Zowe profiles
schemaVersion: 1.0

hosts: 
  - name: default
    host: some.host.com
    user: ibmuser
    services:
      - type: zosmf
        profiles:
          - name: tso1 
            port: 443
          - name: ca11
            port: 444
            rejectUnauthorized: false
```

**Comment by tucker01** [comment]
I like the structure you have proposed. I made some quick changes to mess around and evaluate.

Couple points:
* Using the object key to name profiles automatically protects the user against duplicating entries (profiles of the same name). I think this is a plus when editing by hand. 
* Using the object key to name profiles reduces the amount of code and makes accessing a profile by name simple (no traversing arrays).

**Comment by dkelosky** [comment]
Hi @phaumer - would this work to help with your concerns on generic keys (this doesn't seem to work just yet with yaml / RedHat intellisense)?  
![intellisense-example](https://user-images.githubusercontent.com/14940561/95595127-d5a8c600-0a19-11eb-8f29-a70c911af178.gif)

**Comment by MikeBauerCA** [comment]
Closing as my initial request is accommodated by the new config approach in the `@next` release. Thanks.
