### ISSUE TITLE
Long response times using Zowe CLI

### ISSUE THREAD

**Issue by Rune-Christensen** [zowe/zowe-cli#861]
Hi,
We are experiencing very long response times using the Zowe CLI.
 
We want to fetch a list of all the members in our main COBOL source library.
This library contains approx 280k members.
We tried this using the zOSMF rest interface: 
```
$ time curl -s --insecure -X GET -b "C:\TEMP\.sysvcookies" -H 'X-IBM-Max-Items: 300000' "https://ourzOS/zosmf/restfiles/ds/mainSourceLibrary/member" > members-rest.txt

real    0m2,126s
user    0m0,000s
sys     0m0,000s
```
And then we tried it using the Zowe CLI:
```
$ time zowe zos-files list all-members mainSourceLibrary > members-cli.txt

real    3m10,039s
user    0m0,045s
sys     0m0,167s
```

When running the Zowe CLI command, we see that after a few seconds the output file contains data, and then grows in size until all members are written.
We therefore suspect that it is the processing of the output from zOSMF, that takes a long time.

Is it possible to reduce the time it takes to proces the output?
This is currently a major roadblock for our adoption of using the VSCode Zowe plugin.

Regards
Rune Christensen

**Comment by t1m0thyj** [comment]
Thanks for reporting this! I've been able to reproduce the long response time when running `zowe zos-files list all-members` on a PDS with 300k members.

The performance should be improved once https://github.com/zowe/zowe-cli/pull/868 is merged. On my machine it reduced the response time from >2 min to 15 sec. It may be even less depending on how fast your z/OSMF instance is (since the Curl command took 10 sec for me).

**Comment by t1m0thyj** [comment]
@Rune-Christensen Could you please try v6.24.6 of Zowe CLI which is available on [the NPM registry](https://www.npmjs.com/package/@zowe/cli)? It includes the fix which should improve response time.

**Comment by Rune-Christensen** [comment]
@t1m0thyj I can confirm that response times have improved a lot :-D
Thank you
