### ISSUE TITLE
Upgrade Migration Utility

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-cli#896]
We should develop a utility to help users migrate between the current LTS version of the CLI and our next major version release currently tagged as `@next` on public npm. While no migration may be immediately required, we have deprecated some functionality and could help users transition to the new best practices as soon as possible. The current deprecation that I believe we need a migration utility for is the shift to team level profiles aka single config.

In Zowe CLI v6, there is no project-level config. There is only global config. Therefore, we should only need to migrate v6 global config to v7 global config best practices. We could develop a new migration command in the CLI to accommodate this transition. I like the idea of a separate command over a post-install script so that users opt-in to the new best practices since the old style config will still work in v7. We could also leverage this command for future migrations. 

Some documentation on the current manual upgrade process is available [here](https://github.com/zowe/zowe-cli/blob/next/docs/Early%20Access%20-%20Using%20Global%20Profile%20Configuration.md#installing-next-version)

**Comment by MikeBauerCA** [comment]
Refinement notes:
Includes transition to built-in SCS
Post-install script could prompt, but built-in command would allow them to more easily transition later on. Could rerun install though... benefit of post-install script is it would happen automatically vs users needing to perform a second operation
Conclusion - post-install script is desirable - detect if old config is being used / SCS plug-in is installed.

**Comment by JTonda** [comment]
Additional Notes:

Need to decide both if and how we're going to preserve the profiles and the credentials.

**Comment by t1m0thyj** [comment]
A post-install script may no longer be feasible because of a breaking change introduced in npm@7: [RFC0022](https://github.com/npm/rfcs/blob/latest/implemented/0022-quieter-install-scripts.md)

The new behavior of npm@7 is:
* NPM lifecycle scripts are now run in the background, so they can't write to stdout or stderr.
* If an NPM script fails with a non-zero exit code, then its output is printed and the install will fail.
* The old behavior can be restored by setting `foreground-tasks=true` in NPM config, but this is disabled by default.

**Comment by t1m0thyj** [comment]
**Suggestion:** A new command `zowe profiles migrate`

It may seem strange to add a new command in a deprecated command group, but it seems appropriate in this case since the command should be removed when Zowe CLI completely drops support for old-school profiles.

Proposed behavior for migration utility:

```
$ zowe profiles migrate

Detected 8 profile(s) to be migrated from Zowe v1 to v2.

Are you sure you want to continue? [y/N]

Disabling secure credential store...done
Uninstalling secure credential store...done
Migrating cics profile "lpar1"...done
Migrating db2 profile "lpar1"...done
Migrating ims profile "lpar1"...done
Migrating mq profile "lpar1"...done
Migrating endevor profile "lpar1"...done
Migration endevor-location profile "lpar1"...done
Migrating zosmf profile "lpar1"...done
Migrating zosmf profile "lpar2"...done
Backing up old profiles...done

Your profiles have been migrated successfully.

The new profiles have been saved to /home/user/.zowe/zowe.config.json.
Run "zowe config edit" to open this file in your default editor.

The old profiles have been moved to /home/user/.zowe/profiles-old.
Run "zowe profiles migrate --delete" if you want to completely remove them.
```

After running the migration utility, there are still things left on your system. Running the migrate command with the "--delete" flag will perform the steps above if profiles haven't been migrated yet, as well as the following steps:

```
$ zowe profiles migrate --delete

Warning: This will completely remove Zowe v1 profiles from your system.

Are you sure you want to continue? [y/N]

Deleting secure properties for "@brightside/core"...done
Deleting secure properties for "@zowe/cli"...done
Deleting secure properties for "Zowe-Plugin"...done
Removing old profiles...done

Your old profiles have been deleted successfully.
```

Another possible command would be `zowe profiles migrate --revert`, but we may not want this since Zowe v1 profiles are deprecated and reverting back to them is not recommended.

**Comment by MikeBauerCA** [comment]
Note: 
`zowe profiles migrate` ~8
`zowe profiles migrate --delete` ~3

**Comment by t1m0thyj** [comment]
@MikeBauerCA Since our PI planning meeting today, I've realized that `zowe profiles migrate` would be inconsistent since it adds a command alongside groups (e.g., `zowe profiles create XXX`, `zowe profiles set XXX`, etc). I assume mixing commands and groups at the same level is bad? If so, I'm not sure how we want to handle this - perhaps we could have `zowe profiles migrate disable` and `zowe profiles migrate delete` or something like that.

**Comment by MikeBauerCA** [comment]
Alternatively, we could use `zowe profiles migrate profiles` or `zowe profiles migrate all` ... the last term should be an object, not a verb.

**Comment by zFernand0** [comment]
Should we specify what profiles are being migrated?
For instance `zowe profiles migrate v1-v2`.
Just want to leave our options open in case we need to do something like:
- `zowe profiles migrate prelts-v1`
- `zowe profiles migrate v2-v3`

**Comment by MikeBauerCA** [comment]
@zFernand0 it is definitely a good thought but since the `profiles` command group as a whole is deprecated, it will be gone in the `v3` release.

**Comment by t1m0thyj** [comment]
There is a PoC of the `zowe profiles migrate` command in the "next-migrate-profiles" branch.

For the command name, we may want to use `zowe config migrate-profiles` as suggested by @gejohnston.

**Comment by JTonda** [comment]
Currently leaning towards zowe config convert-profiles but can revisit during implementation.
