### ISSUE TITLE
Secure credentials - JSON path

### ISSUE THREAD

**Issue by VitGottwald** [zowe/zowe-cli#950]
After successfully reseting my password in #949 I got curious about what services and what scope it will be used for. I read `zowe.config.json` again and I stumbled on the "secure" section. It was apparently generated by the initial `zowe config init -g` and looked like this:

```
    "secure": [
        "profiles.my_base.properties.user",
        "profiles.my_base.properties.password"
    ]
```

looking at the structure and the contents of the file I figured the items are likely JSON paths. And it looks like the fields they reference do not exist in the file. I guess they are supplied from the secure credential store when requested.

But this means that if I rename my "my_base" profile, I will lose the secure fields and will have to update the JSON paths in the "secure" section and probably also rerun `zowe config secure` to enter new values for them.

A seemingly simple operation of changing a profile name now requires several steps with opportunities to make an error.

_What would you think about allowing fields that are a `string` by definition (like _username_ and _password_ for example) to also take the shape of `{secure: "key.into.secure.credential.store"}`?_

With such a setup the base profile "my_base" would now look like this:
```
        "my_base": {
            "type": "base",
            "properties": {
                "user": {"secure": "plex1.user"},
                "password": {"secure": "plex1.password"},
                "rejectUnauthorized": false
            }
        }
```
and the "secure" section would no longer be necessary. It would be possible to change the profile name without further steps. The username and password would also be explicitly defined in a location where they are expected.

Please note this is not an original idea. It is quite common in javascript and its tooling (e.g. webpack config) to accept a string value for a basic use case and an object when extra information is needed. In this case if string value is supplied it would represent a plaintext username/password and the object `{secure: "key.into.secure.credential.store"}` would specify that the value comes from secure credential store from an item with a key `key.into.secure.credential.store`.

**Comment by t1m0thyj** [comment]
I like the idea of `{"secure": "key.into.secure.credential.store"}` - agree it makes it easier to see which fields are secure, rather than a "secure" array at bottom of JSON file.

The problem I see with this is that profile properties in Zowe CLI can be any type of object. They're not limited to strings, booleans, and numbers. So if we were to encode information about a profile property in an object, this would be a breaking change. Profiles would no longer be able to store JSON objects like `{"secure": "key.into.secure.credential.store"}`, which they are able to do today.

Perhaps since team config is in the next release and the major version is being bumped, we could allow such a breaking change. I'm not aware of any plugins that store JSON objects in their profiles. However, we'd definitely need to consider the impact of this breaking change before implementing it.

**Comment by VitGottwald** [comment]
Thank you for your response @t1m0thyj ! What I had in mind is to trigger the lookup in credential store only if the field is defined as a "string" in the plugin schema AND has a value of `{"secure": "key.into.secure.credential.store"}`.

Is that something that would be feasible and non-breaking?

**Comment by gejohnston** [comment]
I think that placing a secure value directly in the structure hierarchy (where a user will see it in its proper context) will be easier for a user to find and interpret his/her property values.

From your suggestion, you are probably not aware that we no longer store each secure value as its own key in the OS credential vault. Instead, we store one key (Zowe/secure_config_props) which contains the JSON property name paths and their values for all the secure values in the user's entire configuration. This was done, in part, to avoid multiple prompts to confirm access to the credential vault on the Mac OS. 

The "secure" array makes the retrieval and storage of all secure properties much easier for the code. I suspect it would be possible to instead search the configuration structure for properties marked as "secure" to achieve the same result.

Because each property is not stored in a separate key in the OS credential vault, the value for a secure JSON property may not need to be an object, as you suggest in your proposal. We could possibly just used a reserved keyword string, like "SecurelyStoredInOsCredentialVault". Our code could automatically detect the JSON path from the location of the property itself. We could then store that JsonPath:value pair among the complete set of secure values placed into the credential vault. 

I may be overlooking some technical difficulty, but my point is that I think it sounds feasible to achieve your original goal of placing a secure property in the location where a user would most likely expect to see it.

I am in favor of the Darkside team undertaking an investigation for making such a change in a sprint before the new configuration enhancement is officially delivered. We could also get some input from our UX team during that investigation.

**Comment by tucker01** [comment]
As another point, right now, the secure fields are tied to a particular file path. Implementing (at least some form) of @VitGottwald suggestion would eliminate that. It could also allow for sharing of secured credentials across all profiles.

**Comment by t1m0thyj** [comment]
An alternative idea would be to add a "secure" property that can be defined at the profile level:
```
        "my_base": {
            "type": "base",
            "properties": {
                "rejectUnauthorized": false
            }
            "secure": [
                "user",
                "password"
            ]
        }
```

This approach is kind of a middle ground between the current behavior where "secure" property is at top level of JSON file, and the other suggested approach where "secure" property is at profile property level.

Advantages of this approach:
* Properties are explicitly defined in the location where they are expected, rather than at bottom of file.
* There is no risk of a breaking change for profiles that may want to store JSON objects.
* This may be an easier change to implement than the other approach suggested, since secure properties would still be tied to a specific profile and the way they are stored in the vault could remain the same.

**Comment by VitGottwald** [comment]
Thank you @t1m0thyj! This would certainly bring the secure properties closer to where a user would expect them.

One downside I see here is that it would still require the secrets to be unsealed before they would be passed to any consumer, even if the consumer would only be passing them around in order to be used later e.g. by the REST client as outlined in https://github.com/zowe/zowe-cli/issues/957 .

**Comment by t1m0thyj** [comment]
After discussing this issue with the team and considering several approaches for storing secure credentials, I created a list of advantages and disadvantages for each one: https://gist.github.com/t1m0thyj/c142c668a4353844d469901cf7ce3634
Feel free to provide feedback if it seems to be missing important points 🙂 

> One downside I see here is that it would still require the secrets to be unsealed before they would be passed to any consumer, even if the consumer would only be passing them around in order to be used later e.g. by the REST client as outlined in #957 .

If I understand correctly the idea of #957, it seems like it would make it more difficult for consumers to access profile properties, as for each one they'd have to check whether it is secure or not, and if so unseal it. As long as the Zowe SDK itself does not leak any secure details in logs, I'm not sure how much we need to take responsibility of ensuring that extensions are secure.
