### ISSUE TITLE
Inconsistent zowe files delete Alias

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#983]
For download, you can download `uss-file | uf`:
```
   zowe zos-files download <command>

   Where <command> is one of the following:

 COMMANDS
 --------

   all-members | am Download all members from a pds
   data-set | ds    Download content from a z/OS data set
   uss-file | uf    Download content from a USS file
```

For delete, you can delete `uss-file | uss`:
```
   zowe zos-files delete <command>

   Where <command> is one of the following:

 COMMANDS
 --------

   data-set | ds           Delete a data set or data set member permanently
   data-set-vsam | vsam    Delete a VSAM cluster permanently
   migrated-data-set | mds Delete migrated data sets.
   uss-file | uss          Delete a Unix Systems Services (USS) File or directory
                           permanently
   zos-file-system | zfs   Delete a z/OS file system permanently
```

Should the alias and description be the same?

**Comment by MikeBauerCA** [comment]
I prefer `uss-file | uf` because that is consistent with other command aliases (e.g. `migrated-data-set | mds` and `zos-file-system | zfs`). It would be ideal if we had [hidden alias support](https://github.com/zowe/zowe-cli/issues/36). But, if someone can get to this before then, I would vote for `uss-file | uf | uss` for backwards compatibility and forward consistency.

**Comment by igarshep** [comment]
please assign this to me. looking into it
